import { createFileRoute } from '@tanstack/react-router';
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import { toast } from 'sonner';
import { supabase } from '@/integrations/supabase/client';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Label } from '@/components/ui/label';

export const Route = createFileRoute('/admin/plans')({ component: PlanManagementPage });

type Plan = { id: string; code: string; name: string; description: string; currency: string; active: boolean; max_teams: number | null; max_matches: number | null; max_live_matches: number | null; max_administrators: number | null };
type Duration = { id: string; plan_id: string; label: string; price: number; discount_amount: number; active: boolean };

function PlanManagementPage() {
  const qc = useQueryClient();
  const plans = useQuery({ queryKey: ['admin-subscription-plans'], queryFn: async () => { const { data, error } = await supabase.from('league_subscription_plans' as never).select('*').order('created_at'); if (error) throw error; return (data ?? []) as unknown as Plan[]; } });
  const durations = useQuery({ queryKey: ['admin-subscription-durations'], queryFn: async () => { const { data, error } = await supabase.from('league_subscription_plan_durations' as never).select('*').order('label'); if (error) throw error; return (data ?? []) as unknown as Duration[]; } });
  const savePlan = useMutation({ mutationFn: async ({ id, payload }: { id: string; payload: Partial<Plan> }) => { const { error } = await supabase.from('league_subscription_plans' as never).update(payload as never).eq('id', id); if (error) throw error; }, onSuccess: () => { toast.success('Plan saved'); qc.invalidateQueries({ queryKey: ['admin-subscription-plans'] }); }, onError: (error) => toast.error(error instanceof Error ? error.message : 'Could not save plan') });
  const saveDuration = useMutation({ mutationFn: async ({ id, payload }: { id: string; payload: Partial<Duration> }) => { const { error } = await supabase.from('league_subscription_plan_durations' as never).update(payload as never).eq('id', id); if (error) throw error; }, onSuccess: () => { toast.success('Duration saved'); qc.invalidateQueries({ queryKey: ['admin-subscription-durations'] }); }, onError: (error) => toast.error(error instanceof Error ? error.message : 'Could not save duration') });
  return <div className="space-y-6"><div><h1 className="text-2xl font-bold">Subscription & Plan Management</h1><p className="text-muted-foreground">These values are retrieved by league registration from the database. Changes affect new orders only.</p></div>{plans.isLoading ? <p>Loading plans...</p> : (plans.data ?? []).map((plan) => <Card key={plan.id}><CardHeader><CardTitle>{plan.name}</CardTitle></CardHeader><CardContent><form className="grid gap-3 md:grid-cols-2" onSubmit={(event) => { event.preventDefault(); const fd = new FormData(event.currentTarget); savePlan.mutate({ id: plan.id, payload: { name: String(fd.get('name')), description: String(fd.get('description')), active: fd.get('active') === 'on', max_teams: numeric(fd.get('max_teams')), max_matches: numeric(fd.get('max_matches')), max_live_matches: numeric(fd.get('max_live_matches')), max_administrators: numeric(fd.get('max_administrators')) } }); }}><Field name="name" label="Plan name" defaultValue={plan.name} /><Field name="description" label="Description" defaultValue={plan.description} /><Field name="max_teams" label="Maximum teams" type="number" defaultValue={plan.max_teams ?? ''} /><Field name="max_matches" label="Maximum matches" type="number" defaultValue={plan.max_matches ?? ''} /><Field name="max_live_matches" label="Simultaneous live matches" type="number" defaultValue={plan.max_live_matches ?? ''} /><Field name="max_administrators" label="Administrators" type="number" defaultValue={plan.max_administrators ?? ''} /><label className="flex items-center gap-2 text-sm"><input name="active" type="checkbox" defaultChecked={plan.active} /> Available for new registration</label><Button className="md:col-span-2" disabled={savePlan.isPending}>Save plan</Button></form><div className="mt-5 border-t pt-4"><h3 className="font-medium">Durations and prices</h3><div className="mt-3 grid gap-2">{(durations.data ?? []).filter((duration) => duration.plan_id === plan.id).map((duration) => <form key={duration.id} className="grid items-end gap-2 md:grid-cols-[1fr_1fr_1fr_auto]" onSubmit={(event) => { event.preventDefault(); const fd = new FormData(event.currentTarget); saveDuration.mutate({ id: duration.id, payload: { price: Number(fd.get('price')), discount_amount: Number(fd.get('discount_amount')), active: fd.get('active') === 'on' } }); }}><div><Label>{duration.label}</Label><Input value={duration.label} disabled /></div><Field name="price" label="Price" type="number" defaultValue={duration.price} /><Field name="discount_amount" label="Discount" type="number" defaultValue={duration.discount_amount} /><div className="flex gap-2"><label className="flex items-center gap-1 text-xs"><input name="active" type="checkbox" defaultChecked={duration.active} />Active</label><Button size="sm">Save</Button></div></form>)}</div></div></CardContent></Card>)}</div>;
}
function Field({ name, label, defaultValue, type = 'text' }: { name: string; label: string; defaultValue: string | number; type?: string }) { return <div><Label>{label}</Label><Input name={name} type={type} defaultValue={defaultValue} /></div>; }
function numeric(value: FormDataEntryValue | null) { const number = Number(value); return Number.isFinite(number) && String(value).trim() !== '' ? number : null; }
