import { createFileRoute } from '@tanstack/react-router';
import { useQuery } from '@tanstack/react-query';
import { Clock3, ShieldCheck } from 'lucide-react';
import { supabase } from '@/integrations/supabase/client';
import { PageShell } from '@/components/PageShell';
import { Button } from '@/components/ui/button';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';
export const Route = createFileRoute('/register/payment')({ component: PaymentPage });
function PaymentPage() { const token = new URLSearchParams(window.location.search).get('order') ?? ''; const order = useQuery({ queryKey: ['public-registration-order', token], enabled: !!token, refetchInterval: 15000, queryFn: async () => { const { data, error } = await supabase.rpc('get_public_league_registration_order' as never, { p_token: token } as never); if (error) throw error; return (data as unknown as Array<{ registration_reference: string; league_name: string; plan_name: string; duration_label: string; expected_amount: number; currency: string; payment_status: string; signup_allowed: boolean; signup_available_at: string }> | null)?.[0] ?? null; } }); const data = order.data; return <PageShell><div className="mx-auto max-w-xl py-12"><Card><CardHeader><CardTitle>Payment Verification</CardTitle></CardHeader><CardContent className="space-y-4">{!data ? <p>Loading payment order...</p> : <><dl className="grid gap-3 text-sm"><div>Reference: <strong>{data.registration_reference}</strong></div><div>League: <strong>{data.league_name}</strong></div><div>Subscription: <strong>{data.plan_name} / {data.duration_label}</strong></div><div>Amount: <strong>{data.currency} {Number(data.expected_amount).toLocaleString()}</strong></div></dl><div className="rounded-md border bg-muted/30 p-4 text-sm">{data.payment_status === 'verified' ? <span className="flex gap-2"><ShieldCheck className="h-5 w-5 text-green-600" />Payment verified. You may create your account.</span> : <span className="flex gap-2"><Clock3 className="h-5 w-5" />Payment is pending provider verification. This screen refreshes automatically.</span>}</div>{data.signup_allowed ? <Button className="w-full" onClick={() => window.location.assign(`/auth?registration=${encodeURIComponent(token)}`)}>Proceed to sign up</Button> : <p className="text-sm text-muted-foreground">You may continue account signup after the verification waiting window. Platform access remains locked until payment verification and Super Admin approval.</p>}</>}</CardContent></Card></div></PageShell>; }
