/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LiveRouteImport } from './routes/live'
import { Route as LeaguesRouteImport } from './routes/leagues'
import { Route as HelpRouteImport } from './routes/help'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AccountRouteImport } from './routes/account'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as MatchesIndexRouteImport } from './routes/matches/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as RefereeMatchIdRouteImport } from './routes/referee.$matchId'
import { Route as ModeratorMatchIdRouteImport } from './routes/moderator.$matchId'
import { Route as MatchesIdRouteImport } from './routes/matches/$id'
import { Route as LiveMatchIdRouteImport } from './routes/live.$matchId'
import { Route as LeaguesSlugRouteImport } from './routes/leagues.$slug'
import { Route as DashboardViewerRouteImport } from './routes/dashboard/viewer'
import { Route as DashboardTeamsRouteImport } from './routes/dashboard/teams'
import { Route as DashboardTeamRouteImport } from './routes/dashboard/team'
import { Route as DashboardSponsorRouteImport } from './routes/dashboard/sponsor'
import { Route as DashboardModeratorRouteImport } from './routes/dashboard/moderator'
import { Route as DashboardLeaguesRouteImport } from './routes/dashboard/leagues'
import { Route as DashboardLeagueRouteImport } from './routes/dashboard/league'
import { Route as DashboardCommentatorRouteImport } from './routes/dashboard/commentator'
import { Route as DashboardCoachRouteImport } from './routes/dashboard/coach'
import { Route as DashboardCameraRouteImport } from './routes/dashboard/camera'
import { Route as CommentateMatchIdRouteImport } from './routes/commentate.$matchId'
import { Route as AuthCallbackRouteImport } from './routes/auth/callback'
import { Route as AdminUsersRouteImport } from './routes/admin/users'
import { Route as AdminSlideshowRouteImport } from './routes/admin/slideshow'
import { Route as AdminPaymentsRouteImport } from './routes/admin/payments'
import { Route as AdminModerationRouteImport } from './routes/admin/moderation'
import { Route as AdminAdsRouteImport } from './routes/admin/ads'
import { Route as DashboardTeamRegisterRouteImport } from './routes/dashboard/team/register'
import { Route as DashboardLeagueWalletRouteImport } from './routes/dashboard/league/wallet'
import { Route as DashboardLeagueTeamsRouteImport } from './routes/dashboard/league/teams'
import { Route as DashboardLeagueSettingsRouteImport } from './routes/dashboard/league/settings'
import { Route as DashboardLeagueRulesRouteImport } from './routes/dashboard/league/rules'
import { Route as DashboardLeagueRegisterRouteImport } from './routes/dashboard/league/register'
import { Route as DashboardLeagueModeratorsRouteImport } from './routes/dashboard/league/moderators'
import { Route as DashboardLeagueMatchesRouteImport } from './routes/dashboard/league/matches'
import { Route as DashboardLeagueBroadcastRouteImport } from './routes/dashboard/league/broadcast'
import { Route as DashboardLeagueLeagueIdRouteImport } from './routes/dashboard/league/$leagueId'
import { Route as DashboardTeamPlayersRegisterRouteImport } from './routes/dashboard/team/players/register'

const LiveRoute = LiveRouteImport.update({
  id: '/live',
  path: '/live',
  getParentRoute: () => rootRouteImport,
} as any)
const LeaguesRoute = LeaguesRouteImport.update({
  id: '/leagues',
  path: '/leagues',
  getParentRoute: () => rootRouteImport,
} as any)
const HelpRoute = HelpRouteImport.update({
  id: '/help',
  path: '/help',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountRoute = AccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const MatchesIndexRoute = MatchesIndexRouteImport.update({
  id: '/matches/',
  path: '/matches/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const RefereeMatchIdRoute = RefereeMatchIdRouteImport.update({
  id: '/referee/$matchId',
  path: '/referee/$matchId',
  getParentRoute: () => rootRouteImport,
} as any)
const ModeratorMatchIdRoute = ModeratorMatchIdRouteImport.update({
  id: '/moderator/$matchId',
  path: '/moderator/$matchId',
  getParentRoute: () => rootRouteImport,
} as any)
const MatchesIdRoute = MatchesIdRouteImport.update({
  id: '/matches/$id',
  path: '/matches/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const LiveMatchIdRoute = LiveMatchIdRouteImport.update({
  id: '/$matchId',
  path: '/$matchId',
  getParentRoute: () => LiveRoute,
} as any)
const LeaguesSlugRoute = LeaguesSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => LeaguesRoute,
} as any)
const DashboardViewerRoute = DashboardViewerRouteImport.update({
  id: '/viewer',
  path: '/viewer',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardTeamsRoute = DashboardTeamsRouteImport.update({
  id: '/teams',
  path: '/teams',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardTeamRoute = DashboardTeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardSponsorRoute = DashboardSponsorRouteImport.update({
  id: '/sponsor',
  path: '/sponsor',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardModeratorRoute = DashboardModeratorRouteImport.update({
  id: '/moderator',
  path: '/moderator',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardLeaguesRoute = DashboardLeaguesRouteImport.update({
  id: '/leagues',
  path: '/leagues',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardLeagueRoute = DashboardLeagueRouteImport.update({
  id: '/league',
  path: '/league',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardCommentatorRoute = DashboardCommentatorRouteImport.update({
  id: '/commentator',
  path: '/commentator',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardCoachRoute = DashboardCoachRouteImport.update({
  id: '/coach',
  path: '/coach',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardCameraRoute = DashboardCameraRouteImport.update({
  id: '/camera',
  path: '/camera',
  getParentRoute: () => DashboardRoute,
} as any)
const CommentateMatchIdRoute = CommentateMatchIdRouteImport.update({
  id: '/commentate/$matchId',
  path: '/commentate/$matchId',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/callback',
  path: '/callback',
  getParentRoute: () => AuthRoute,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSlideshowRoute = AdminSlideshowRouteImport.update({
  id: '/slideshow',
  path: '/slideshow',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPaymentsRoute = AdminPaymentsRouteImport.update({
  id: '/payments',
  path: '/payments',
  getParentRoute: () => AdminRoute,
} as any)
const AdminModerationRoute = AdminModerationRouteImport.update({
  id: '/moderation',
  path: '/moderation',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAdsRoute = AdminAdsRouteImport.update({
  id: '/ads',
  path: '/ads',
  getParentRoute: () => AdminRoute,
} as any)
const DashboardTeamRegisterRoute = DashboardTeamRegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => DashboardTeamRoute,
} as any)
const DashboardLeagueWalletRoute = DashboardLeagueWalletRouteImport.update({
  id: '/wallet',
  path: '/wallet',
  getParentRoute: () => DashboardLeagueRoute,
} as any)
const DashboardLeagueTeamsRoute = DashboardLeagueTeamsRouteImport.update({
  id: '/teams',
  path: '/teams',
  getParentRoute: () => DashboardLeagueRoute,
} as any)
const DashboardLeagueSettingsRoute = DashboardLeagueSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => DashboardLeagueRoute,
} as any)
const DashboardLeagueRulesRoute = DashboardLeagueRulesRouteImport.update({
  id: '/rules',
  path: '/rules',
  getParentRoute: () => DashboardLeagueRoute,
} as any)
const DashboardLeagueRegisterRoute = DashboardLeagueRegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => DashboardLeagueRoute,
} as any)
const DashboardLeagueModeratorsRoute =
  DashboardLeagueModeratorsRouteImport.update({
    id: '/moderators',
    path: '/moderators',
    getParentRoute: () => DashboardLeagueRoute,
  } as any)
const DashboardLeagueMatchesRoute = DashboardLeagueMatchesRouteImport.update({
  id: '/matches',
  path: '/matches',
  getParentRoute: () => DashboardLeagueRoute,
} as any)
const DashboardLeagueBroadcastRoute =
  DashboardLeagueBroadcastRouteImport.update({
    id: '/broadcast',
    path: '/broadcast',
    getParentRoute: () => DashboardLeagueRoute,
  } as any)
const DashboardLeagueLeagueIdRoute = DashboardLeagueLeagueIdRouteImport.update({
  id: '/$leagueId',
  path: '/$leagueId',
  getParentRoute: () => DashboardLeagueRoute,
} as any)
const DashboardTeamPlayersRegisterRoute =
  DashboardTeamPlayersRegisterRouteImport.update({
    id: '/players/register',
    path: '/players/register',
    getParentRoute: () => DashboardTeamRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/account': typeof AccountRoute
  '/admin': typeof AdminRouteWithChildren
  '/auth': typeof AuthRouteWithChildren
  '/dashboard': typeof DashboardRouteWithChildren
  '/help': typeof HelpRoute
  '/leagues': typeof LeaguesRouteWithChildren
  '/live': typeof LiveRouteWithChildren
  '/admin/ads': typeof AdminAdsRoute
  '/admin/moderation': typeof AdminModerationRoute
  '/admin/payments': typeof AdminPaymentsRoute
  '/admin/slideshow': typeof AdminSlideshowRoute
  '/admin/users': typeof AdminUsersRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/commentate/$matchId': typeof CommentateMatchIdRoute
  '/dashboard/camera': typeof DashboardCameraRoute
  '/dashboard/coach': typeof DashboardCoachRoute
  '/dashboard/commentator': typeof DashboardCommentatorRoute
  '/dashboard/league': typeof DashboardLeagueRouteWithChildren
  '/dashboard/leagues': typeof DashboardLeaguesRoute
  '/dashboard/moderator': typeof DashboardModeratorRoute
  '/dashboard/sponsor': typeof DashboardSponsorRoute
  '/dashboard/team': typeof DashboardTeamRouteWithChildren
  '/dashboard/teams': typeof DashboardTeamsRoute
  '/dashboard/viewer': typeof DashboardViewerRoute
  '/leagues/$slug': typeof LeaguesSlugRoute
  '/live/$matchId': typeof LiveMatchIdRoute
  '/matches/$id': typeof MatchesIdRoute
  '/moderator/$matchId': typeof ModeratorMatchIdRoute
  '/referee/$matchId': typeof RefereeMatchIdRoute
  '/admin/': typeof AdminIndexRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/matches/': typeof MatchesIndexRoute
  '/dashboard/league/$leagueId': typeof DashboardLeagueLeagueIdRoute
  '/dashboard/league/broadcast': typeof DashboardLeagueBroadcastRoute
  '/dashboard/league/matches': typeof DashboardLeagueMatchesRoute
  '/dashboard/league/moderators': typeof DashboardLeagueModeratorsRoute
  '/dashboard/league/register': typeof DashboardLeagueRegisterRoute
  '/dashboard/league/rules': typeof DashboardLeagueRulesRoute
  '/dashboard/league/settings': typeof DashboardLeagueSettingsRoute
  '/dashboard/league/teams': typeof DashboardLeagueTeamsRoute
  '/dashboard/league/wallet': typeof DashboardLeagueWalletRoute
  '/dashboard/team/register': typeof DashboardTeamRegisterRoute
  '/dashboard/team/players/register': typeof DashboardTeamPlayersRegisterRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/account': typeof AccountRoute
  '/auth': typeof AuthRouteWithChildren
  '/help': typeof HelpRoute
  '/leagues': typeof LeaguesRouteWithChildren
  '/live': typeof LiveRouteWithChildren
  '/admin/ads': typeof AdminAdsRoute
  '/admin/moderation': typeof AdminModerationRoute
  '/admin/payments': typeof AdminPaymentsRoute
  '/admin/slideshow': typeof AdminSlideshowRoute
  '/admin/users': typeof AdminUsersRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/commentate/$matchId': typeof CommentateMatchIdRoute
  '/dashboard/camera': typeof DashboardCameraRoute
  '/dashboard/coach': typeof DashboardCoachRoute
  '/dashboard/commentator': typeof DashboardCommentatorRoute
  '/dashboard/league': typeof DashboardLeagueRouteWithChildren
  '/dashboard/leagues': typeof DashboardLeaguesRoute
  '/dashboard/moderator': typeof DashboardModeratorRoute
  '/dashboard/sponsor': typeof DashboardSponsorRoute
  '/dashboard/team': typeof DashboardTeamRouteWithChildren
  '/dashboard/teams': typeof DashboardTeamsRoute
  '/dashboard/viewer': typeof DashboardViewerRoute
  '/leagues/$slug': typeof LeaguesSlugRoute
  '/live/$matchId': typeof LiveMatchIdRoute
  '/matches/$id': typeof MatchesIdRoute
  '/moderator/$matchId': typeof ModeratorMatchIdRoute
  '/referee/$matchId': typeof RefereeMatchIdRoute
  '/admin': typeof AdminIndexRoute
  '/dashboard': typeof DashboardIndexRoute
  '/matches': typeof MatchesIndexRoute
  '/dashboard/league/$leagueId': typeof DashboardLeagueLeagueIdRoute
  '/dashboard/league/broadcast': typeof DashboardLeagueBroadcastRoute
  '/dashboard/league/matches': typeof DashboardLeagueMatchesRoute
  '/dashboard/league/moderators': typeof DashboardLeagueModeratorsRoute
  '/dashboard/league/register': typeof DashboardLeagueRegisterRoute
  '/dashboard/league/rules': typeof DashboardLeagueRulesRoute
  '/dashboard/league/settings': typeof DashboardLeagueSettingsRoute
  '/dashboard/league/teams': typeof DashboardLeagueTeamsRoute
  '/dashboard/league/wallet': typeof DashboardLeagueWalletRoute
  '/dashboard/team/register': typeof DashboardTeamRegisterRoute
  '/dashboard/team/players/register': typeof DashboardTeamPlayersRegisterRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/account': typeof AccountRoute
  '/admin': typeof AdminRouteWithChildren
  '/auth': typeof AuthRouteWithChildren
  '/dashboard': typeof DashboardRouteWithChildren
  '/help': typeof HelpRoute
  '/leagues': typeof LeaguesRouteWithChildren
  '/live': typeof LiveRouteWithChildren
  '/admin/ads': typeof AdminAdsRoute
  '/admin/moderation': typeof AdminModerationRoute
  '/admin/payments': typeof AdminPaymentsRoute
  '/admin/slideshow': typeof AdminSlideshowRoute
  '/admin/users': typeof AdminUsersRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/commentate/$matchId': typeof CommentateMatchIdRoute
  '/dashboard/camera': typeof DashboardCameraRoute
  '/dashboard/coach': typeof DashboardCoachRoute
  '/dashboard/commentator': typeof DashboardCommentatorRoute
  '/dashboard/league': typeof DashboardLeagueRouteWithChildren
  '/dashboard/leagues': typeof DashboardLeaguesRoute
  '/dashboard/moderator': typeof DashboardModeratorRoute
  '/dashboard/sponsor': typeof DashboardSponsorRoute
  '/dashboard/team': typeof DashboardTeamRouteWithChildren
  '/dashboard/teams': typeof DashboardTeamsRoute
  '/dashboard/viewer': typeof DashboardViewerRoute
  '/leagues/$slug': typeof LeaguesSlugRoute
  '/live/$matchId': typeof LiveMatchIdRoute
  '/matches/$id': typeof MatchesIdRoute
  '/moderator/$matchId': typeof ModeratorMatchIdRoute
  '/referee/$matchId': typeof RefereeMatchIdRoute
  '/admin/': typeof AdminIndexRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/matches/': typeof MatchesIndexRoute
  '/dashboard/league/$leagueId': typeof DashboardLeagueLeagueIdRoute
  '/dashboard/league/broadcast': typeof DashboardLeagueBroadcastRoute
  '/dashboard/league/matches': typeof DashboardLeagueMatchesRoute
  '/dashboard/league/moderators': typeof DashboardLeagueModeratorsRoute
  '/dashboard/league/register': typeof DashboardLeagueRegisterRoute
  '/dashboard/league/rules': typeof DashboardLeagueRulesRoute
  '/dashboard/league/settings': typeof DashboardLeagueSettingsRoute
  '/dashboard/league/teams': typeof DashboardLeagueTeamsRoute
  '/dashboard/league/wallet': typeof DashboardLeagueWalletRoute
  '/dashboard/team/register': typeof DashboardTeamRegisterRoute
  '/dashboard/team/players/register': typeof DashboardTeamPlayersRegisterRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/account'
    | '/admin'
    | '/auth'
    | '/dashboard'
    | '/help'
    | '/leagues'
    | '/live'
    | '/admin/ads'
    | '/admin/moderation'
    | '/admin/payments'
    | '/admin/slideshow'
    | '/admin/users'
    | '/auth/callback'
    | '/commentate/$matchId'
    | '/dashboard/camera'
    | '/dashboard/coach'
    | '/dashboard/commentator'
    | '/dashboard/league'
    | '/dashboard/leagues'
    | '/dashboard/moderator'
    | '/dashboard/sponsor'
    | '/dashboard/team'
    | '/dashboard/teams'
    | '/dashboard/viewer'
    | '/leagues/$slug'
    | '/live/$matchId'
    | '/matches/$id'
    | '/moderator/$matchId'
    | '/referee/$matchId'
    | '/admin/'
    | '/dashboard/'
    | '/matches/'
    | '/dashboard/league/$leagueId'
    | '/dashboard/league/broadcast'
    | '/dashboard/league/matches'
    | '/dashboard/league/moderators'
    | '/dashboard/league/register'
    | '/dashboard/league/rules'
    | '/dashboard/league/settings'
    | '/dashboard/league/teams'
    | '/dashboard/league/wallet'
    | '/dashboard/team/register'
    | '/dashboard/team/players/register'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/account'
    | '/auth'
    | '/help'
    | '/leagues'
    | '/live'
    | '/admin/ads'
    | '/admin/moderation'
    | '/admin/payments'
    | '/admin/slideshow'
    | '/admin/users'
    | '/auth/callback'
    | '/commentate/$matchId'
    | '/dashboard/camera'
    | '/dashboard/coach'
    | '/dashboard/commentator'
    | '/dashboard/league'
    | '/dashboard/leagues'
    | '/dashboard/moderator'
    | '/dashboard/sponsor'
    | '/dashboard/team'
    | '/dashboard/teams'
    | '/dashboard/viewer'
    | '/leagues/$slug'
    | '/live/$matchId'
    | '/matches/$id'
    | '/moderator/$matchId'
    | '/referee/$matchId'
    | '/admin'
    | '/dashboard'
    | '/matches'
    | '/dashboard/league/$leagueId'
    | '/dashboard/league/broadcast'
    | '/dashboard/league/matches'
    | '/dashboard/league/moderators'
    | '/dashboard/league/register'
    | '/dashboard/league/rules'
    | '/dashboard/league/settings'
    | '/dashboard/league/teams'
    | '/dashboard/league/wallet'
    | '/dashboard/team/register'
    | '/dashboard/team/players/register'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/account'
    | '/admin'
    | '/auth'
    | '/dashboard'
    | '/help'
    | '/leagues'
    | '/live'
    | '/admin/ads'
    | '/admin/moderation'
    | '/admin/payments'
    | '/admin/slideshow'
    | '/admin/users'
    | '/auth/callback'
    | '/commentate/$matchId'
    | '/dashboard/camera'
    | '/dashboard/coach'
    | '/dashboard/commentator'
    | '/dashboard/league'
    | '/dashboard/leagues'
    | '/dashboard/moderator'
    | '/dashboard/sponsor'
    | '/dashboard/team'
    | '/dashboard/teams'
    | '/dashboard/viewer'
    | '/leagues/$slug'
    | '/live/$matchId'
    | '/matches/$id'
    | '/moderator/$matchId'
    | '/referee/$matchId'
    | '/admin/'
    | '/dashboard/'
    | '/matches/'
    | '/dashboard/league/$leagueId'
    | '/dashboard/league/broadcast'
    | '/dashboard/league/matches'
    | '/dashboard/league/moderators'
    | '/dashboard/league/register'
    | '/dashboard/league/rules'
    | '/dashboard/league/settings'
    | '/dashboard/league/teams'
    | '/dashboard/league/wallet'
    | '/dashboard/team/register'
    | '/dashboard/team/players/register'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AccountRoute: typeof AccountRoute
  AdminRoute: typeof AdminRouteWithChildren
  AuthRoute: typeof AuthRouteWithChildren
  DashboardRoute: typeof DashboardRouteWithChildren
  HelpRoute: typeof HelpRoute
  LeaguesRoute: typeof LeaguesRouteWithChildren
  LiveRoute: typeof LiveRouteWithChildren
  CommentateMatchIdRoute: typeof CommentateMatchIdRoute
  MatchesIdRoute: typeof MatchesIdRoute
  ModeratorMatchIdRoute: typeof ModeratorMatchIdRoute
  RefereeMatchIdRoute: typeof RefereeMatchIdRoute
  MatchesIndexRoute: typeof MatchesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/live': {
      id: '/live'
      path: '/live'
      fullPath: '/live'
      preLoaderRoute: typeof LiveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leagues': {
      id: '/leagues'
      path: '/leagues'
      fullPath: '/leagues'
      preLoaderRoute: typeof LeaguesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/help': {
      id: '/help'
      path: '/help'
      fullPath: '/help'
      preLoaderRoute: typeof HelpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account': {
      id: '/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/matches/': {
      id: '/matches/'
      path: '/matches'
      fullPath: '/matches/'
      preLoaderRoute: typeof MatchesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/referee/$matchId': {
      id: '/referee/$matchId'
      path: '/referee/$matchId'
      fullPath: '/referee/$matchId'
      preLoaderRoute: typeof RefereeMatchIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/moderator/$matchId': {
      id: '/moderator/$matchId'
      path: '/moderator/$matchId'
      fullPath: '/moderator/$matchId'
      preLoaderRoute: typeof ModeratorMatchIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/matches/$id': {
      id: '/matches/$id'
      path: '/matches/$id'
      fullPath: '/matches/$id'
      preLoaderRoute: typeof MatchesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/live/$matchId': {
      id: '/live/$matchId'
      path: '/$matchId'
      fullPath: '/live/$matchId'
      preLoaderRoute: typeof LiveMatchIdRouteImport
      parentRoute: typeof LiveRoute
    }
    '/leagues/$slug': {
      id: '/leagues/$slug'
      path: '/$slug'
      fullPath: '/leagues/$slug'
      preLoaderRoute: typeof LeaguesSlugRouteImport
      parentRoute: typeof LeaguesRoute
    }
    '/dashboard/viewer': {
      id: '/dashboard/viewer'
      path: '/viewer'
      fullPath: '/dashboard/viewer'
      preLoaderRoute: typeof DashboardViewerRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/teams': {
      id: '/dashboard/teams'
      path: '/teams'
      fullPath: '/dashboard/teams'
      preLoaderRoute: typeof DashboardTeamsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/team': {
      id: '/dashboard/team'
      path: '/team'
      fullPath: '/dashboard/team'
      preLoaderRoute: typeof DashboardTeamRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/sponsor': {
      id: '/dashboard/sponsor'
      path: '/sponsor'
      fullPath: '/dashboard/sponsor'
      preLoaderRoute: typeof DashboardSponsorRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/moderator': {
      id: '/dashboard/moderator'
      path: '/moderator'
      fullPath: '/dashboard/moderator'
      preLoaderRoute: typeof DashboardModeratorRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/leagues': {
      id: '/dashboard/leagues'
      path: '/leagues'
      fullPath: '/dashboard/leagues'
      preLoaderRoute: typeof DashboardLeaguesRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/league': {
      id: '/dashboard/league'
      path: '/league'
      fullPath: '/dashboard/league'
      preLoaderRoute: typeof DashboardLeagueRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/commentator': {
      id: '/dashboard/commentator'
      path: '/commentator'
      fullPath: '/dashboard/commentator'
      preLoaderRoute: typeof DashboardCommentatorRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/coach': {
      id: '/dashboard/coach'
      path: '/coach'
      fullPath: '/dashboard/coach'
      preLoaderRoute: typeof DashboardCoachRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/camera': {
      id: '/dashboard/camera'
      path: '/camera'
      fullPath: '/dashboard/camera'
      preLoaderRoute: typeof DashboardCameraRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/commentate/$matchId': {
      id: '/commentate/$matchId'
      path: '/commentate/$matchId'
      fullPath: '/commentate/$matchId'
      preLoaderRoute: typeof CommentateMatchIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof AuthRoute
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/slideshow': {
      id: '/admin/slideshow'
      path: '/slideshow'
      fullPath: '/admin/slideshow'
      preLoaderRoute: typeof AdminSlideshowRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/payments': {
      id: '/admin/payments'
      path: '/payments'
      fullPath: '/admin/payments'
      preLoaderRoute: typeof AdminPaymentsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/moderation': {
      id: '/admin/moderation'
      path: '/moderation'
      fullPath: '/admin/moderation'
      preLoaderRoute: typeof AdminModerationRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/ads': {
      id: '/admin/ads'
      path: '/ads'
      fullPath: '/admin/ads'
      preLoaderRoute: typeof AdminAdsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/dashboard/team/register': {
      id: '/dashboard/team/register'
      path: '/register'
      fullPath: '/dashboard/team/register'
      preLoaderRoute: typeof DashboardTeamRegisterRouteImport
      parentRoute: typeof DashboardTeamRoute
    }
    '/dashboard/league/wallet': {
      id: '/dashboard/league/wallet'
      path: '/wallet'
      fullPath: '/dashboard/league/wallet'
      preLoaderRoute: typeof DashboardLeagueWalletRouteImport
      parentRoute: typeof DashboardLeagueRoute
    }
    '/dashboard/league/teams': {
      id: '/dashboard/league/teams'
      path: '/teams'
      fullPath: '/dashboard/league/teams'
      preLoaderRoute: typeof DashboardLeagueTeamsRouteImport
      parentRoute: typeof DashboardLeagueRoute
    }
    '/dashboard/league/settings': {
      id: '/dashboard/league/settings'
      path: '/settings'
      fullPath: '/dashboard/league/settings'
      preLoaderRoute: typeof DashboardLeagueSettingsRouteImport
      parentRoute: typeof DashboardLeagueRoute
    }
    '/dashboard/league/rules': {
      id: '/dashboard/league/rules'
      path: '/rules'
      fullPath: '/dashboard/league/rules'
      preLoaderRoute: typeof DashboardLeagueRulesRouteImport
      parentRoute: typeof DashboardLeagueRoute
    }
    '/dashboard/league/register': {
      id: '/dashboard/league/register'
      path: '/register'
      fullPath: '/dashboard/league/register'
      preLoaderRoute: typeof DashboardLeagueRegisterRouteImport
      parentRoute: typeof DashboardLeagueRoute
    }
    '/dashboard/league/moderators': {
      id: '/dashboard/league/moderators'
      path: '/moderators'
      fullPath: '/dashboard/league/moderators'
      preLoaderRoute: typeof DashboardLeagueModeratorsRouteImport
      parentRoute: typeof DashboardLeagueRoute
    }
    '/dashboard/league/matches': {
      id: '/dashboard/league/matches'
      path: '/matches'
      fullPath: '/dashboard/league/matches'
      preLoaderRoute: typeof DashboardLeagueMatchesRouteImport
      parentRoute: typeof DashboardLeagueRoute
    }
    '/dashboard/league/broadcast': {
      id: '/dashboard/league/broadcast'
      path: '/broadcast'
      fullPath: '/dashboard/league/broadcast'
      preLoaderRoute: typeof DashboardLeagueBroadcastRouteImport
      parentRoute: typeof DashboardLeagueRoute
    }
    '/dashboard/league/$leagueId': {
      id: '/dashboard/league/$leagueId'
      path: '/$leagueId'
      fullPath: '/dashboard/league/$leagueId'
      preLoaderRoute: typeof DashboardLeagueLeagueIdRouteImport
      parentRoute: typeof DashboardLeagueRoute
    }
    '/dashboard/team/players/register': {
      id: '/dashboard/team/players/register'
      path: '/players/register'
      fullPath: '/dashboard/team/players/register'
      preLoaderRoute: typeof DashboardTeamPlayersRegisterRouteImport
      parentRoute: typeof DashboardTeamRoute
    }
  }
}

interface AdminRouteChildren {
  AdminAdsRoute: typeof AdminAdsRoute
  AdminModerationRoute: typeof AdminModerationRoute
  AdminPaymentsRoute: typeof AdminPaymentsRoute
  AdminSlideshowRoute: typeof AdminSlideshowRoute
  AdminUsersRoute: typeof AdminUsersRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAdsRoute: AdminAdsRoute,
  AdminModerationRoute: AdminModerationRoute,
  AdminPaymentsRoute: AdminPaymentsRoute,
  AdminSlideshowRoute: AdminSlideshowRoute,
  AdminUsersRoute: AdminUsersRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface AuthRouteChildren {
  AuthCallbackRoute: typeof AuthCallbackRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthCallbackRoute: AuthCallbackRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

interface DashboardLeagueRouteChildren {
  DashboardLeagueLeagueIdRoute: typeof DashboardLeagueLeagueIdRoute
  DashboardLeagueBroadcastRoute: typeof DashboardLeagueBroadcastRoute
  DashboardLeagueMatchesRoute: typeof DashboardLeagueMatchesRoute
  DashboardLeagueModeratorsRoute: typeof DashboardLeagueModeratorsRoute
  DashboardLeagueRegisterRoute: typeof DashboardLeagueRegisterRoute
  DashboardLeagueRulesRoute: typeof DashboardLeagueRulesRoute
  DashboardLeagueSettingsRoute: typeof DashboardLeagueSettingsRoute
  DashboardLeagueTeamsRoute: typeof DashboardLeagueTeamsRoute
  DashboardLeagueWalletRoute: typeof DashboardLeagueWalletRoute
}

const DashboardLeagueRouteChildren: DashboardLeagueRouteChildren = {
  DashboardLeagueLeagueIdRoute: DashboardLeagueLeagueIdRoute,
  DashboardLeagueBroadcastRoute: DashboardLeagueBroadcastRoute,
  DashboardLeagueMatchesRoute: DashboardLeagueMatchesRoute,
  DashboardLeagueModeratorsRoute: DashboardLeagueModeratorsRoute,
  DashboardLeagueRegisterRoute: DashboardLeagueRegisterRoute,
  DashboardLeagueRulesRoute: DashboardLeagueRulesRoute,
  DashboardLeagueSettingsRoute: DashboardLeagueSettingsRoute,
  DashboardLeagueTeamsRoute: DashboardLeagueTeamsRoute,
  DashboardLeagueWalletRoute: DashboardLeagueWalletRoute,
}

const DashboardLeagueRouteWithChildren = DashboardLeagueRoute._addFileChildren(
  DashboardLeagueRouteChildren,
)

interface DashboardTeamRouteChildren {
  DashboardTeamRegisterRoute: typeof DashboardTeamRegisterRoute
  DashboardTeamPlayersRegisterRoute: typeof DashboardTeamPlayersRegisterRoute
}

const DashboardTeamRouteChildren: DashboardTeamRouteChildren = {
  DashboardTeamRegisterRoute: DashboardTeamRegisterRoute,
  DashboardTeamPlayersRegisterRoute: DashboardTeamPlayersRegisterRoute,
}

const DashboardTeamRouteWithChildren = DashboardTeamRoute._addFileChildren(
  DashboardTeamRouteChildren,
)

interface DashboardRouteChildren {
  DashboardCameraRoute: typeof DashboardCameraRoute
  DashboardCoachRoute: typeof DashboardCoachRoute
  DashboardCommentatorRoute: typeof DashboardCommentatorRoute
  DashboardLeagueRoute: typeof DashboardLeagueRouteWithChildren
  DashboardLeaguesRoute: typeof DashboardLeaguesRoute
  DashboardModeratorRoute: typeof DashboardModeratorRoute
  DashboardSponsorRoute: typeof DashboardSponsorRoute
  DashboardTeamRoute: typeof DashboardTeamRouteWithChildren
  DashboardTeamsRoute: typeof DashboardTeamsRoute
  DashboardViewerRoute: typeof DashboardViewerRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardCameraRoute: DashboardCameraRoute,
  DashboardCoachRoute: DashboardCoachRoute,
  DashboardCommentatorRoute: DashboardCommentatorRoute,
  DashboardLeagueRoute: DashboardLeagueRouteWithChildren,
  DashboardLeaguesRoute: DashboardLeaguesRoute,
  DashboardModeratorRoute: DashboardModeratorRoute,
  DashboardSponsorRoute: DashboardSponsorRoute,
  DashboardTeamRoute: DashboardTeamRouteWithChildren,
  DashboardTeamsRoute: DashboardTeamsRoute,
  DashboardViewerRoute: DashboardViewerRoute,
  DashboardIndexRoute: DashboardIndexRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

interface LeaguesRouteChildren {
  LeaguesSlugRoute: typeof LeaguesSlugRoute
}

const LeaguesRouteChildren: LeaguesRouteChildren = {
  LeaguesSlugRoute: LeaguesSlugRoute,
}

const LeaguesRouteWithChildren =
  LeaguesRoute._addFileChildren(LeaguesRouteChildren)

interface LiveRouteChildren {
  LiveMatchIdRoute: typeof LiveMatchIdRoute
}

const LiveRouteChildren: LiveRouteChildren = {
  LiveMatchIdRoute: LiveMatchIdRoute,
}

const LiveRouteWithChildren = LiveRoute._addFileChildren(LiveRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AccountRoute: AccountRoute,
  AdminRoute: AdminRouteWithChildren,
  AuthRoute: AuthRouteWithChildren,
  DashboardRoute: DashboardRouteWithChildren,
  HelpRoute: HelpRoute,
  LeaguesRoute: LeaguesRouteWithChildren,
  LiveRoute: LiveRouteWithChildren,
  CommentateMatchIdRoute: CommentateMatchIdRoute,
  MatchesIdRoute: MatchesIdRoute,
  ModeratorMatchIdRoute: ModeratorMatchIdRoute,
  RefereeMatchIdRoute: RefereeMatchIdRoute,
  MatchesIndexRoute: MatchesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
