/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TeamsRouteImport } from './routes/teams'
import { Route as LiveRouteImport } from './routes/live'
import { Route as LeaguesRouteImport } from './routes/leagues'
import { Route as HelpRouteImport } from './routes/help'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AccountRouteImport } from './routes/account'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as MatchesIndexRouteImport } from './routes/matches/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as TeamsSlugRouteImport } from './routes/teams.$slug'
import { Route as RegisterTeamRouteImport } from './routes/register/team'
import { Route as RegisterLeagueRouteImport } from './routes/register/league'
import { Route as RefereeMatchIdRouteImport } from './routes/referee.$matchId'
import { Route as ModeratorMatchIdRouteImport } from './routes/moderator.$matchId'
import { Route as MatchesIdRouteImport } from './routes/matches/$id'
import { Route as LiveMatchIdRouteImport } from './routes/live.$matchId'
import { Route as LegalTermsRouteImport } from './routes/legal/terms'
import { Route as LegalPrivacyRouteImport } from './routes/legal/privacy'
import { Route as LeaguesSlugRouteImport } from './routes/leagues.$slug'
import { Route as DashboardViewerRouteImport } from './routes/dashboard/viewer'
import { Route as DashboardTeamsRouteImport } from './routes/dashboard/teams'
import { Route as DashboardTeamRouteImport } from './routes/dashboard/team'
import { Route as DashboardSponsorRouteImport } from './routes/dashboard/sponsor'
import { Route as DashboardModeratorRouteImport } from './routes/dashboard/moderator'
import { Route as DashboardLeaguesRouteImport } from './routes/dashboard/leagues'
import { Route as DashboardLeagueRouteImport } from './routes/dashboard/league'
import { Route as DashboardCommentatorRouteImport } from './routes/dashboard/commentator'
import { Route as DashboardCoachRouteImport } from './routes/dashboard/coach'
import { Route as DashboardCameraRouteImport } from './routes/dashboard/camera'
import { Route as CommentateMatchIdRouteImport } from './routes/commentate.$matchId'
import { Route as AuthCallbackRouteImport } from './routes/auth/callback'
import { Route as AdminUsersRouteImport } from './routes/admin/users'
import { Route as AdminSlideshowRouteImport } from './routes/admin/slideshow'
import { Route as AdminPaymentsRouteImport } from './routes/admin/payments'
import { Route as AdminModerationRouteImport } from './routes/admin/moderation'
import { Route as AdminAdsRouteImport } from './routes/admin/ads'
import { Route as ShareMatchIdRouteImport } from './routes/share/match/$id'
import { Route as DashboardViewerProfileRouteImport } from './routes/dashboard/viewer/profile'
import { Route as DashboardViewerPredictionsRouteImport } from './routes/dashboard/viewer/predictions'
import { Route as DashboardViewerHighlightsRouteImport } from './routes/dashboard/viewer/highlights'
import { Route as DashboardViewerFollowingRouteImport } from './routes/dashboard/viewer/following'
import { Route as DashboardViewerChatRouteImport } from './routes/dashboard/viewer/chat'
import { Route as DashboardTeamSquadRouteImport } from './routes/dashboard/team/squad'
import { Route as DashboardTeamRegisterRouteImport } from './routes/dashboard/team/register'
import { Route as DashboardTeamProfileRouteImport } from './routes/dashboard/team/profile'
import { Route as DashboardTeamMediaRouteImport } from './routes/dashboard/team/media'
import { Route as DashboardTeamMatchesRouteImport } from './routes/dashboard/team/matches'
import { Route as DashboardTeamFormationsRouteImport } from './routes/dashboard/team/formations'
import { Route as DashboardModeratorVarRouteImport } from './routes/dashboard/moderator/var'
import { Route as DashboardModeratorStatisticsRouteImport } from './routes/dashboard/moderator/statistics'
import { Route as DashboardModeratorReplayRouteImport } from './routes/dashboard/moderator/replay'
import { Route as DashboardModeratorGraphicsRouteImport } from './routes/dashboard/moderator/graphics'
import { Route as DashboardModeratorEventsRouteImport } from './routes/dashboard/moderator/events'
import { Route as DashboardModeratorCamerasRouteImport } from './routes/dashboard/moderator/cameras'
import { Route as DashboardModeratorBroadcastRouteImport } from './routes/dashboard/moderator/broadcast'
import { Route as DashboardModeratorAnnouncementsRouteImport } from './routes/dashboard/moderator/announcements'
import { Route as DashboardLeagueWalletRouteImport } from './routes/dashboard/league/wallet'
import { Route as DashboardLeagueTeamsRouteImport } from './routes/dashboard/league/teams'
import { Route as DashboardLeagueSettingsRouteImport } from './routes/dashboard/league/settings'
import { Route as DashboardLeagueRulesRouteImport } from './routes/dashboard/league/rules'
import { Route as DashboardLeagueRegisterRouteImport } from './routes/dashboard/league/register'
import { Route as DashboardLeagueModeratorsRouteImport } from './routes/dashboard/league/moderators'
import { Route as DashboardLeagueMatchesRouteImport } from './routes/dashboard/league/matches'
import { Route as DashboardLeagueBroadcastRouteImport } from './routes/dashboard/league/broadcast'
import { Route as DashboardLeagueLeagueIdRouteImport } from './routes/dashboard/league/$leagueId'
import { Route as DashboardCoachTrainingRouteImport } from './routes/dashboard/coach/training'
import { Route as DashboardCoachTacticsRouteImport } from './routes/dashboard/coach/tactics'
import { Route as DashboardCoachSquadRouteImport } from './routes/dashboard/coach/squad'
import { Route as DashboardCoachPerformanceRouteImport } from './routes/dashboard/coach/performance'
import { Route as DashboardCoachMedicalRouteImport } from './routes/dashboard/coach/medical'
import { Route as DashboardCoachMatchesRouteImport } from './routes/dashboard/coach/matches'
import { Route as DashboardCoachLineupsRouteImport } from './routes/dashboard/coach/lineups'
import { Route as DashboardCoachFormationsRouteImport } from './routes/dashboard/coach/formations'
import { Route as DashboardTeamPlayersRegisterRouteImport } from './routes/dashboard/team/players/register'

const TeamsRoute = TeamsRouteImport.update({
  id: '/teams',
  path: '/teams',
  getParentRoute: () => rootRouteImport,
} as any)
const LiveRoute = LiveRouteImport.update({
  id: '/live',
  path: '/live',
  getParentRoute: () => rootRouteImport,
} as any)
const LeaguesRoute = LeaguesRouteImport.update({
  id: '/leagues',
  path: '/leagues',
  getParentRoute: () => rootRouteImport,
} as any)
const HelpRoute = HelpRouteImport.update({
  id: '/help',
  path: '/help',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountRoute = AccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const MatchesIndexRoute = MatchesIndexRouteImport.update({
  id: '/matches/',
  path: '/matches/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const TeamsSlugRoute = TeamsSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => TeamsRoute,
} as any)
const RegisterTeamRoute = RegisterTeamRouteImport.update({
  id: '/register/team',
  path: '/register/team',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterLeagueRoute = RegisterLeagueRouteImport.update({
  id: '/register/league',
  path: '/register/league',
  getParentRoute: () => rootRouteImport,
} as any)
const RefereeMatchIdRoute = RefereeMatchIdRouteImport.update({
  id: '/referee/$matchId',
  path: '/referee/$matchId',
  getParentRoute: () => rootRouteImport,
} as any)
const ModeratorMatchIdRoute = ModeratorMatchIdRouteImport.update({
  id: '/moderator/$matchId',
  path: '/moderator/$matchId',
  getParentRoute: () => rootRouteImport,
} as any)
const MatchesIdRoute = MatchesIdRouteImport.update({
  id: '/matches/$id',
  path: '/matches/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const LiveMatchIdRoute = LiveMatchIdRouteImport.update({
  id: '/$matchId',
  path: '/$matchId',
  getParentRoute: () => LiveRoute,
} as any)
const LegalTermsRoute = LegalTermsRouteImport.update({
  id: '/legal/terms',
  path: '/legal/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalPrivacyRoute = LegalPrivacyRouteImport.update({
  id: '/legal/privacy',
  path: '/legal/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const LeaguesSlugRoute = LeaguesSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => LeaguesRoute,
} as any)
const DashboardViewerRoute = DashboardViewerRouteImport.update({
  id: '/viewer',
  path: '/viewer',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardTeamsRoute = DashboardTeamsRouteImport.update({
  id: '/teams',
  path: '/teams',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardTeamRoute = DashboardTeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardSponsorRoute = DashboardSponsorRouteImport.update({
  id: '/sponsor',
  path: '/sponsor',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardModeratorRoute = DashboardModeratorRouteImport.update({
  id: '/moderator',
  path: '/moderator',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardLeaguesRoute = DashboardLeaguesRouteImport.update({
  id: '/leagues',
  path: '/leagues',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardLeagueRoute = DashboardLeagueRouteImport.update({
  id: '/league',
  path: '/league',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardCommentatorRoute = DashboardCommentatorRouteImport.update({
  id: '/commentator',
  path: '/commentator',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardCoachRoute = DashboardCoachRouteImport.update({
  id: '/coach',
  path: '/coach',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardCameraRoute = DashboardCameraRouteImport.update({
  id: '/camera',
  path: '/camera',
  getParentRoute: () => DashboardRoute,
} as any)
const CommentateMatchIdRoute = CommentateMatchIdRouteImport.update({
  id: '/commentate/$matchId',
  path: '/commentate/$matchId',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/callback',
  path: '/callback',
  getParentRoute: () => AuthRoute,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSlideshowRoute = AdminSlideshowRouteImport.update({
  id: '/slideshow',
  path: '/slideshow',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPaymentsRoute = AdminPaymentsRouteImport.update({
  id: '/payments',
  path: '/payments',
  getParentRoute: () => AdminRoute,
} as any)
const AdminModerationRoute = AdminModerationRouteImport.update({
  id: '/moderation',
  path: '/moderation',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAdsRoute = AdminAdsRouteImport.update({
  id: '/ads',
  path: '/ads',
  getParentRoute: () => AdminRoute,
} as any)
const ShareMatchIdRoute = ShareMatchIdRouteImport.update({
  id: '/share/match/$id',
  path: '/share/match/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardViewerProfileRoute = DashboardViewerProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => DashboardViewerRoute,
} as any)
const DashboardViewerPredictionsRoute =
  DashboardViewerPredictionsRouteImport.update({
    id: '/predictions',
    path: '/predictions',
    getParentRoute: () => DashboardViewerRoute,
  } as any)
const DashboardViewerHighlightsRoute =
  DashboardViewerHighlightsRouteImport.update({
    id: '/highlights',
    path: '/highlights',
    getParentRoute: () => DashboardViewerRoute,
  } as any)
const DashboardViewerFollowingRoute =
  DashboardViewerFollowingRouteImport.update({
    id: '/following',
    path: '/following',
    getParentRoute: () => DashboardViewerRoute,
  } as any)
const DashboardViewerChatRoute = DashboardViewerChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => DashboardViewerRoute,
} as any)
const DashboardTeamSquadRoute = DashboardTeamSquadRouteImport.update({
  id: '/squad',
  path: '/squad',
  getParentRoute: () => DashboardTeamRoute,
} as any)
const DashboardTeamRegisterRoute = DashboardTeamRegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => DashboardTeamRoute,
} as any)
const DashboardTeamProfileRoute = DashboardTeamProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => DashboardTeamRoute,
} as any)
const DashboardTeamMediaRoute = DashboardTeamMediaRouteImport.update({
  id: '/media',
  path: '/media',
  getParentRoute: () => DashboardTeamRoute,
} as any)
const DashboardTeamMatchesRoute = DashboardTeamMatchesRouteImport.update({
  id: '/matches',
  path: '/matches',
  getParentRoute: () => DashboardTeamRoute,
} as any)
const DashboardTeamFormationsRoute = DashboardTeamFormationsRouteImport.update({
  id: '/formations',
  path: '/formations',
  getParentRoute: () => DashboardTeamRoute,
} as any)
const DashboardModeratorVarRoute = DashboardModeratorVarRouteImport.update({
  id: '/var',
  path: '/var',
  getParentRoute: () => DashboardModeratorRoute,
} as any)
const DashboardModeratorStatisticsRoute =
  DashboardModeratorStatisticsRouteImport.update({
    id: '/statistics',
    path: '/statistics',
    getParentRoute: () => DashboardModeratorRoute,
  } as any)
const DashboardModeratorReplayRoute =
  DashboardModeratorReplayRouteImport.update({
    id: '/replay',
    path: '/replay',
    getParentRoute: () => DashboardModeratorRoute,
  } as any)
const DashboardModeratorGraphicsRoute =
  DashboardModeratorGraphicsRouteImport.update({
    id: '/graphics',
    path: '/graphics',
    getParentRoute: () => DashboardModeratorRoute,
  } as any)
const DashboardModeratorEventsRoute =
  DashboardModeratorEventsRouteImport.update({
    id: '/events',
    path: '/events',
    getParentRoute: () => DashboardModeratorRoute,
  } as any)
const DashboardModeratorCamerasRoute =
  DashboardModeratorCamerasRouteImport.update({
    id: '/cameras',
    path: '/cameras',
    getParentRoute: () => DashboardModeratorRoute,
  } as any)
const DashboardModeratorBroadcastRoute =
  DashboardModeratorBroadcastRouteImport.update({
    id: '/broadcast',
    path: '/broadcast',
    getParentRoute: () => DashboardModeratorRoute,
  } as any)
const DashboardModeratorAnnouncementsRoute =
  DashboardModeratorAnnouncementsRouteImport.update({
    id: '/announcements',
    path: '/announcements',
    getParentRoute: () => DashboardModeratorRoute,
  } as any)
const DashboardLeagueWalletRoute = DashboardLeagueWalletRouteImport.update({
  id: '/wallet',
  path: '/wallet',
  getParentRoute: () => DashboardLeagueRoute,
} as any)
const DashboardLeagueTeamsRoute = DashboardLeagueTeamsRouteImport.update({
  id: '/teams',
  path: '/teams',
  getParentRoute: () => DashboardLeagueRoute,
} as any)
const DashboardLeagueSettingsRoute = DashboardLeagueSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => DashboardLeagueRoute,
} as any)
const DashboardLeagueRulesRoute = DashboardLeagueRulesRouteImport.update({
  id: '/rules',
  path: '/rules',
  getParentRoute: () => DashboardLeagueRoute,
} as any)
const DashboardLeagueRegisterRoute = DashboardLeagueRegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => DashboardLeagueRoute,
} as any)
const DashboardLeagueModeratorsRoute =
  DashboardLeagueModeratorsRouteImport.update({
    id: '/moderators',
    path: '/moderators',
    getParentRoute: () => DashboardLeagueRoute,
  } as any)
const DashboardLeagueMatchesRoute = DashboardLeagueMatchesRouteImport.update({
  id: '/matches',
  path: '/matches',
  getParentRoute: () => DashboardLeagueRoute,
} as any)
const DashboardLeagueBroadcastRoute =
  DashboardLeagueBroadcastRouteImport.update({
    id: '/broadcast',
    path: '/broadcast',
    getParentRoute: () => DashboardLeagueRoute,
  } as any)
const DashboardLeagueLeagueIdRoute = DashboardLeagueLeagueIdRouteImport.update({
  id: '/$leagueId',
  path: '/$leagueId',
  getParentRoute: () => DashboardLeagueRoute,
} as any)
const DashboardCoachTrainingRoute = DashboardCoachTrainingRouteImport.update({
  id: '/training',
  path: '/training',
  getParentRoute: () => DashboardCoachRoute,
} as any)
const DashboardCoachTacticsRoute = DashboardCoachTacticsRouteImport.update({
  id: '/tactics',
  path: '/tactics',
  getParentRoute: () => DashboardCoachRoute,
} as any)
const DashboardCoachSquadRoute = DashboardCoachSquadRouteImport.update({
  id: '/squad',
  path: '/squad',
  getParentRoute: () => DashboardCoachRoute,
} as any)
const DashboardCoachPerformanceRoute =
  DashboardCoachPerformanceRouteImport.update({
    id: '/performance',
    path: '/performance',
    getParentRoute: () => DashboardCoachRoute,
  } as any)
const DashboardCoachMedicalRoute = DashboardCoachMedicalRouteImport.update({
  id: '/medical',
  path: '/medical',
  getParentRoute: () => DashboardCoachRoute,
} as any)
const DashboardCoachMatchesRoute = DashboardCoachMatchesRouteImport.update({
  id: '/matches',
  path: '/matches',
  getParentRoute: () => DashboardCoachRoute,
} as any)
const DashboardCoachLineupsRoute = DashboardCoachLineupsRouteImport.update({
  id: '/lineups',
  path: '/lineups',
  getParentRoute: () => DashboardCoachRoute,
} as any)
const DashboardCoachFormationsRoute =
  DashboardCoachFormationsRouteImport.update({
    id: '/formations',
    path: '/formations',
    getParentRoute: () => DashboardCoachRoute,
  } as any)
const DashboardTeamPlayersRegisterRoute =
  DashboardTeamPlayersRegisterRouteImport.update({
    id: '/players/register',
    path: '/players/register',
    getParentRoute: () => DashboardTeamRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/account': typeof AccountRoute
  '/admin': typeof AdminRouteWithChildren
  '/auth': typeof AuthRouteWithChildren
  '/dashboard': typeof DashboardRouteWithChildren
  '/help': typeof HelpRoute
  '/leagues': typeof LeaguesRouteWithChildren
  '/live': typeof LiveRouteWithChildren
  '/teams': typeof TeamsRouteWithChildren
  '/admin/ads': typeof AdminAdsRoute
  '/admin/moderation': typeof AdminModerationRoute
  '/admin/payments': typeof AdminPaymentsRoute
  '/admin/slideshow': typeof AdminSlideshowRoute
  '/admin/users': typeof AdminUsersRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/commentate/$matchId': typeof CommentateMatchIdRoute
  '/dashboard/camera': typeof DashboardCameraRoute
  '/dashboard/coach': typeof DashboardCoachRouteWithChildren
  '/dashboard/commentator': typeof DashboardCommentatorRoute
  '/dashboard/league': typeof DashboardLeagueRouteWithChildren
  '/dashboard/leagues': typeof DashboardLeaguesRoute
  '/dashboard/moderator': typeof DashboardModeratorRouteWithChildren
  '/dashboard/sponsor': typeof DashboardSponsorRoute
  '/dashboard/team': typeof DashboardTeamRouteWithChildren
  '/dashboard/teams': typeof DashboardTeamsRoute
  '/dashboard/viewer': typeof DashboardViewerRouteWithChildren
  '/leagues/$slug': typeof LeaguesSlugRoute
  '/legal/privacy': typeof LegalPrivacyRoute
  '/legal/terms': typeof LegalTermsRoute
  '/live/$matchId': typeof LiveMatchIdRoute
  '/matches/$id': typeof MatchesIdRoute
  '/moderator/$matchId': typeof ModeratorMatchIdRoute
  '/referee/$matchId': typeof RefereeMatchIdRoute
  '/register/league': typeof RegisterLeagueRoute
  '/register/team': typeof RegisterTeamRoute
  '/teams/$slug': typeof TeamsSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/matches/': typeof MatchesIndexRoute
  '/dashboard/coach/formations': typeof DashboardCoachFormationsRoute
  '/dashboard/coach/lineups': typeof DashboardCoachLineupsRoute
  '/dashboard/coach/matches': typeof DashboardCoachMatchesRoute
  '/dashboard/coach/medical': typeof DashboardCoachMedicalRoute
  '/dashboard/coach/performance': typeof DashboardCoachPerformanceRoute
  '/dashboard/coach/squad': typeof DashboardCoachSquadRoute
  '/dashboard/coach/tactics': typeof DashboardCoachTacticsRoute
  '/dashboard/coach/training': typeof DashboardCoachTrainingRoute
  '/dashboard/league/$leagueId': typeof DashboardLeagueLeagueIdRoute
  '/dashboard/league/broadcast': typeof DashboardLeagueBroadcastRoute
  '/dashboard/league/matches': typeof DashboardLeagueMatchesRoute
  '/dashboard/league/moderators': typeof DashboardLeagueModeratorsRoute
  '/dashboard/league/register': typeof DashboardLeagueRegisterRoute
  '/dashboard/league/rules': typeof DashboardLeagueRulesRoute
  '/dashboard/league/settings': typeof DashboardLeagueSettingsRoute
  '/dashboard/league/teams': typeof DashboardLeagueTeamsRoute
  '/dashboard/league/wallet': typeof DashboardLeagueWalletRoute
  '/dashboard/moderator/announcements': typeof DashboardModeratorAnnouncementsRoute
  '/dashboard/moderator/broadcast': typeof DashboardModeratorBroadcastRoute
  '/dashboard/moderator/cameras': typeof DashboardModeratorCamerasRoute
  '/dashboard/moderator/events': typeof DashboardModeratorEventsRoute
  '/dashboard/moderator/graphics': typeof DashboardModeratorGraphicsRoute
  '/dashboard/moderator/replay': typeof DashboardModeratorReplayRoute
  '/dashboard/moderator/statistics': typeof DashboardModeratorStatisticsRoute
  '/dashboard/moderator/var': typeof DashboardModeratorVarRoute
  '/dashboard/team/formations': typeof DashboardTeamFormationsRoute
  '/dashboard/team/matches': typeof DashboardTeamMatchesRoute
  '/dashboard/team/media': typeof DashboardTeamMediaRoute
  '/dashboard/team/profile': typeof DashboardTeamProfileRoute
  '/dashboard/team/register': typeof DashboardTeamRegisterRoute
  '/dashboard/team/squad': typeof DashboardTeamSquadRoute
  '/dashboard/viewer/chat': typeof DashboardViewerChatRoute
  '/dashboard/viewer/following': typeof DashboardViewerFollowingRoute
  '/dashboard/viewer/highlights': typeof DashboardViewerHighlightsRoute
  '/dashboard/viewer/predictions': typeof DashboardViewerPredictionsRoute
  '/dashboard/viewer/profile': typeof DashboardViewerProfileRoute
  '/share/match/$id': typeof ShareMatchIdRoute
  '/dashboard/team/players/register': typeof DashboardTeamPlayersRegisterRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/account': typeof AccountRoute
  '/auth': typeof AuthRouteWithChildren
  '/help': typeof HelpRoute
  '/leagues': typeof LeaguesRouteWithChildren
  '/live': typeof LiveRouteWithChildren
  '/teams': typeof TeamsRouteWithChildren
  '/admin/ads': typeof AdminAdsRoute
  '/admin/moderation': typeof AdminModerationRoute
  '/admin/payments': typeof AdminPaymentsRoute
  '/admin/slideshow': typeof AdminSlideshowRoute
  '/admin/users': typeof AdminUsersRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/commentate/$matchId': typeof CommentateMatchIdRoute
  '/dashboard/camera': typeof DashboardCameraRoute
  '/dashboard/coach': typeof DashboardCoachRouteWithChildren
  '/dashboard/commentator': typeof DashboardCommentatorRoute
  '/dashboard/league': typeof DashboardLeagueRouteWithChildren
  '/dashboard/leagues': typeof DashboardLeaguesRoute
  '/dashboard/moderator': typeof DashboardModeratorRouteWithChildren
  '/dashboard/sponsor': typeof DashboardSponsorRoute
  '/dashboard/team': typeof DashboardTeamRouteWithChildren
  '/dashboard/teams': typeof DashboardTeamsRoute
  '/dashboard/viewer': typeof DashboardViewerRouteWithChildren
  '/leagues/$slug': typeof LeaguesSlugRoute
  '/legal/privacy': typeof LegalPrivacyRoute
  '/legal/terms': typeof LegalTermsRoute
  '/live/$matchId': typeof LiveMatchIdRoute
  '/matches/$id': typeof MatchesIdRoute
  '/moderator/$matchId': typeof ModeratorMatchIdRoute
  '/referee/$matchId': typeof RefereeMatchIdRoute
  '/register/league': typeof RegisterLeagueRoute
  '/register/team': typeof RegisterTeamRoute
  '/teams/$slug': typeof TeamsSlugRoute
  '/admin': typeof AdminIndexRoute
  '/dashboard': typeof DashboardIndexRoute
  '/matches': typeof MatchesIndexRoute
  '/dashboard/coach/formations': typeof DashboardCoachFormationsRoute
  '/dashboard/coach/lineups': typeof DashboardCoachLineupsRoute
  '/dashboard/coach/matches': typeof DashboardCoachMatchesRoute
  '/dashboard/coach/medical': typeof DashboardCoachMedicalRoute
  '/dashboard/coach/performance': typeof DashboardCoachPerformanceRoute
  '/dashboard/coach/squad': typeof DashboardCoachSquadRoute
  '/dashboard/coach/tactics': typeof DashboardCoachTacticsRoute
  '/dashboard/coach/training': typeof DashboardCoachTrainingRoute
  '/dashboard/league/$leagueId': typeof DashboardLeagueLeagueIdRoute
  '/dashboard/league/broadcast': typeof DashboardLeagueBroadcastRoute
  '/dashboard/league/matches': typeof DashboardLeagueMatchesRoute
  '/dashboard/league/moderators': typeof DashboardLeagueModeratorsRoute
  '/dashboard/league/register': typeof DashboardLeagueRegisterRoute
  '/dashboard/league/rules': typeof DashboardLeagueRulesRoute
  '/dashboard/league/settings': typeof DashboardLeagueSettingsRoute
  '/dashboard/league/teams': typeof DashboardLeagueTeamsRoute
  '/dashboard/league/wallet': typeof DashboardLeagueWalletRoute
  '/dashboard/moderator/announcements': typeof DashboardModeratorAnnouncementsRoute
  '/dashboard/moderator/broadcast': typeof DashboardModeratorBroadcastRoute
  '/dashboard/moderator/cameras': typeof DashboardModeratorCamerasRoute
  '/dashboard/moderator/events': typeof DashboardModeratorEventsRoute
  '/dashboard/moderator/graphics': typeof DashboardModeratorGraphicsRoute
  '/dashboard/moderator/replay': typeof DashboardModeratorReplayRoute
  '/dashboard/moderator/statistics': typeof DashboardModeratorStatisticsRoute
  '/dashboard/moderator/var': typeof DashboardModeratorVarRoute
  '/dashboard/team/formations': typeof DashboardTeamFormationsRoute
  '/dashboard/team/matches': typeof DashboardTeamMatchesRoute
  '/dashboard/team/media': typeof DashboardTeamMediaRoute
  '/dashboard/team/profile': typeof DashboardTeamProfileRoute
  '/dashboard/team/register': typeof DashboardTeamRegisterRoute
  '/dashboard/team/squad': typeof DashboardTeamSquadRoute
  '/dashboard/viewer/chat': typeof DashboardViewerChatRoute
  '/dashboard/viewer/following': typeof DashboardViewerFollowingRoute
  '/dashboard/viewer/highlights': typeof DashboardViewerHighlightsRoute
  '/dashboard/viewer/predictions': typeof DashboardViewerPredictionsRoute
  '/dashboard/viewer/profile': typeof DashboardViewerProfileRoute
  '/share/match/$id': typeof ShareMatchIdRoute
  '/dashboard/team/players/register': typeof DashboardTeamPlayersRegisterRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/account': typeof AccountRoute
  '/admin': typeof AdminRouteWithChildren
  '/auth': typeof AuthRouteWithChildren
  '/dashboard': typeof DashboardRouteWithChildren
  '/help': typeof HelpRoute
  '/leagues': typeof LeaguesRouteWithChildren
  '/live': typeof LiveRouteWithChildren
  '/teams': typeof TeamsRouteWithChildren
  '/admin/ads': typeof AdminAdsRoute
  '/admin/moderation': typeof AdminModerationRoute
  '/admin/payments': typeof AdminPaymentsRoute
  '/admin/slideshow': typeof AdminSlideshowRoute
  '/admin/users': typeof AdminUsersRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/commentate/$matchId': typeof CommentateMatchIdRoute
  '/dashboard/camera': typeof DashboardCameraRoute
  '/dashboard/coach': typeof DashboardCoachRouteWithChildren
  '/dashboard/commentator': typeof DashboardCommentatorRoute
  '/dashboard/league': typeof DashboardLeagueRouteWithChildren
  '/dashboard/leagues': typeof DashboardLeaguesRoute
  '/dashboard/moderator': typeof DashboardModeratorRouteWithChildren
  '/dashboard/sponsor': typeof DashboardSponsorRoute
  '/dashboard/team': typeof DashboardTeamRouteWithChildren
  '/dashboard/teams': typeof DashboardTeamsRoute
  '/dashboard/viewer': typeof DashboardViewerRouteWithChildren
  '/leagues/$slug': typeof LeaguesSlugRoute
  '/legal/privacy': typeof LegalPrivacyRoute
  '/legal/terms': typeof LegalTermsRoute
  '/live/$matchId': typeof LiveMatchIdRoute
  '/matches/$id': typeof MatchesIdRoute
  '/moderator/$matchId': typeof ModeratorMatchIdRoute
  '/referee/$matchId': typeof RefereeMatchIdRoute
  '/register/league': typeof RegisterLeagueRoute
  '/register/team': typeof RegisterTeamRoute
  '/teams/$slug': typeof TeamsSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/matches/': typeof MatchesIndexRoute
  '/dashboard/coach/formations': typeof DashboardCoachFormationsRoute
  '/dashboard/coach/lineups': typeof DashboardCoachLineupsRoute
  '/dashboard/coach/matches': typeof DashboardCoachMatchesRoute
  '/dashboard/coach/medical': typeof DashboardCoachMedicalRoute
  '/dashboard/coach/performance': typeof DashboardCoachPerformanceRoute
  '/dashboard/coach/squad': typeof DashboardCoachSquadRoute
  '/dashboard/coach/tactics': typeof DashboardCoachTacticsRoute
  '/dashboard/coach/training': typeof DashboardCoachTrainingRoute
  '/dashboard/league/$leagueId': typeof DashboardLeagueLeagueIdRoute
  '/dashboard/league/broadcast': typeof DashboardLeagueBroadcastRoute
  '/dashboard/league/matches': typeof DashboardLeagueMatchesRoute
  '/dashboard/league/moderators': typeof DashboardLeagueModeratorsRoute
  '/dashboard/league/register': typeof DashboardLeagueRegisterRoute
  '/dashboard/league/rules': typeof DashboardLeagueRulesRoute
  '/dashboard/league/settings': typeof DashboardLeagueSettingsRoute
  '/dashboard/league/teams': typeof DashboardLeagueTeamsRoute
  '/dashboard/league/wallet': typeof DashboardLeagueWalletRoute
  '/dashboard/moderator/announcements': typeof DashboardModeratorAnnouncementsRoute
  '/dashboard/moderator/broadcast': typeof DashboardModeratorBroadcastRoute
  '/dashboard/moderator/cameras': typeof DashboardModeratorCamerasRoute
  '/dashboard/moderator/events': typeof DashboardModeratorEventsRoute
  '/dashboard/moderator/graphics': typeof DashboardModeratorGraphicsRoute
  '/dashboard/moderator/replay': typeof DashboardModeratorReplayRoute
  '/dashboard/moderator/statistics': typeof DashboardModeratorStatisticsRoute
  '/dashboard/moderator/var': typeof DashboardModeratorVarRoute
  '/dashboard/team/formations': typeof DashboardTeamFormationsRoute
  '/dashboard/team/matches': typeof DashboardTeamMatchesRoute
  '/dashboard/team/media': typeof DashboardTeamMediaRoute
  '/dashboard/team/profile': typeof DashboardTeamProfileRoute
  '/dashboard/team/register': typeof DashboardTeamRegisterRoute
  '/dashboard/team/squad': typeof DashboardTeamSquadRoute
  '/dashboard/viewer/chat': typeof DashboardViewerChatRoute
  '/dashboard/viewer/following': typeof DashboardViewerFollowingRoute
  '/dashboard/viewer/highlights': typeof DashboardViewerHighlightsRoute
  '/dashboard/viewer/predictions': typeof DashboardViewerPredictionsRoute
  '/dashboard/viewer/profile': typeof DashboardViewerProfileRoute
  '/share/match/$id': typeof ShareMatchIdRoute
  '/dashboard/team/players/register': typeof DashboardTeamPlayersRegisterRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/account'
    | '/admin'
    | '/auth'
    | '/dashboard'
    | '/help'
    | '/leagues'
    | '/live'
    | '/teams'
    | '/admin/ads'
    | '/admin/moderation'
    | '/admin/payments'
    | '/admin/slideshow'
    | '/admin/users'
    | '/auth/callback'
    | '/commentate/$matchId'
    | '/dashboard/camera'
    | '/dashboard/coach'
    | '/dashboard/commentator'
    | '/dashboard/league'
    | '/dashboard/leagues'
    | '/dashboard/moderator'
    | '/dashboard/sponsor'
    | '/dashboard/team'
    | '/dashboard/teams'
    | '/dashboard/viewer'
    | '/leagues/$slug'
    | '/legal/privacy'
    | '/legal/terms'
    | '/live/$matchId'
    | '/matches/$id'
    | '/moderator/$matchId'
    | '/referee/$matchId'
    | '/register/league'
    | '/register/team'
    | '/teams/$slug'
    | '/admin/'
    | '/dashboard/'
    | '/matches/'
    | '/dashboard/coach/formations'
    | '/dashboard/coach/lineups'
    | '/dashboard/coach/matches'
    | '/dashboard/coach/medical'
    | '/dashboard/coach/performance'
    | '/dashboard/coach/squad'
    | '/dashboard/coach/tactics'
    | '/dashboard/coach/training'
    | '/dashboard/league/$leagueId'
    | '/dashboard/league/broadcast'
    | '/dashboard/league/matches'
    | '/dashboard/league/moderators'
    | '/dashboard/league/register'
    | '/dashboard/league/rules'
    | '/dashboard/league/settings'
    | '/dashboard/league/teams'
    | '/dashboard/league/wallet'
    | '/dashboard/moderator/announcements'
    | '/dashboard/moderator/broadcast'
    | '/dashboard/moderator/cameras'
    | '/dashboard/moderator/events'
    | '/dashboard/moderator/graphics'
    | '/dashboard/moderator/replay'
    | '/dashboard/moderator/statistics'
    | '/dashboard/moderator/var'
    | '/dashboard/team/formations'
    | '/dashboard/team/matches'
    | '/dashboard/team/media'
    | '/dashboard/team/profile'
    | '/dashboard/team/register'
    | '/dashboard/team/squad'
    | '/dashboard/viewer/chat'
    | '/dashboard/viewer/following'
    | '/dashboard/viewer/highlights'
    | '/dashboard/viewer/predictions'
    | '/dashboard/viewer/profile'
    | '/share/match/$id'
    | '/dashboard/team/players/register'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/account'
    | '/auth'
    | '/help'
    | '/leagues'
    | '/live'
    | '/teams'
    | '/admin/ads'
    | '/admin/moderation'
    | '/admin/payments'
    | '/admin/slideshow'
    | '/admin/users'
    | '/auth/callback'
    | '/commentate/$matchId'
    | '/dashboard/camera'
    | '/dashboard/coach'
    | '/dashboard/commentator'
    | '/dashboard/league'
    | '/dashboard/leagues'
    | '/dashboard/moderator'
    | '/dashboard/sponsor'
    | '/dashboard/team'
    | '/dashboard/teams'
    | '/dashboard/viewer'
    | '/leagues/$slug'
    | '/legal/privacy'
    | '/legal/terms'
    | '/live/$matchId'
    | '/matches/$id'
    | '/moderator/$matchId'
    | '/referee/$matchId'
    | '/register/league'
    | '/register/team'
    | '/teams/$slug'
    | '/admin'
    | '/dashboard'
    | '/matches'
    | '/dashboard/coach/formations'
    | '/dashboard/coach/lineups'
    | '/dashboard/coach/matches'
    | '/dashboard/coach/medical'
    | '/dashboard/coach/performance'
    | '/dashboard/coach/squad'
    | '/dashboard/coach/tactics'
    | '/dashboard/coach/training'
    | '/dashboard/league/$leagueId'
    | '/dashboard/league/broadcast'
    | '/dashboard/league/matches'
    | '/dashboard/league/moderators'
    | '/dashboard/league/register'
    | '/dashboard/league/rules'
    | '/dashboard/league/settings'
    | '/dashboard/league/teams'
    | '/dashboard/league/wallet'
    | '/dashboard/moderator/announcements'
    | '/dashboard/moderator/broadcast'
    | '/dashboard/moderator/cameras'
    | '/dashboard/moderator/events'
    | '/dashboard/moderator/graphics'
    | '/dashboard/moderator/replay'
    | '/dashboard/moderator/statistics'
    | '/dashboard/moderator/var'
    | '/dashboard/team/formations'
    | '/dashboard/team/matches'
    | '/dashboard/team/media'
    | '/dashboard/team/profile'
    | '/dashboard/team/register'
    | '/dashboard/team/squad'
    | '/dashboard/viewer/chat'
    | '/dashboard/viewer/following'
    | '/dashboard/viewer/highlights'
    | '/dashboard/viewer/predictions'
    | '/dashboard/viewer/profile'
    | '/share/match/$id'
    | '/dashboard/team/players/register'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/account'
    | '/admin'
    | '/auth'
    | '/dashboard'
    | '/help'
    | '/leagues'
    | '/live'
    | '/teams'
    | '/admin/ads'
    | '/admin/moderation'
    | '/admin/payments'
    | '/admin/slideshow'
    | '/admin/users'
    | '/auth/callback'
    | '/commentate/$matchId'
    | '/dashboard/camera'
    | '/dashboard/coach'
    | '/dashboard/commentator'
    | '/dashboard/league'
    | '/dashboard/leagues'
    | '/dashboard/moderator'
    | '/dashboard/sponsor'
    | '/dashboard/team'
    | '/dashboard/teams'
    | '/dashboard/viewer'
    | '/leagues/$slug'
    | '/legal/privacy'
    | '/legal/terms'
    | '/live/$matchId'
    | '/matches/$id'
    | '/moderator/$matchId'
    | '/referee/$matchId'
    | '/register/league'
    | '/register/team'
    | '/teams/$slug'
    | '/admin/'
    | '/dashboard/'
    | '/matches/'
    | '/dashboard/coach/formations'
    | '/dashboard/coach/lineups'
    | '/dashboard/coach/matches'
    | '/dashboard/coach/medical'
    | '/dashboard/coach/performance'
    | '/dashboard/coach/squad'
    | '/dashboard/coach/tactics'
    | '/dashboard/coach/training'
    | '/dashboard/league/$leagueId'
    | '/dashboard/league/broadcast'
    | '/dashboard/league/matches'
    | '/dashboard/league/moderators'
    | '/dashboard/league/register'
    | '/dashboard/league/rules'
    | '/dashboard/league/settings'
    | '/dashboard/league/teams'
    | '/dashboard/league/wallet'
    | '/dashboard/moderator/announcements'
    | '/dashboard/moderator/broadcast'
    | '/dashboard/moderator/cameras'
    | '/dashboard/moderator/events'
    | '/dashboard/moderator/graphics'
    | '/dashboard/moderator/replay'
    | '/dashboard/moderator/statistics'
    | '/dashboard/moderator/var'
    | '/dashboard/team/formations'
    | '/dashboard/team/matches'
    | '/dashboard/team/media'
    | '/dashboard/team/profile'
    | '/dashboard/team/register'
    | '/dashboard/team/squad'
    | '/dashboard/viewer/chat'
    | '/dashboard/viewer/following'
    | '/dashboard/viewer/highlights'
    | '/dashboard/viewer/predictions'
    | '/dashboard/viewer/profile'
    | '/share/match/$id'
    | '/dashboard/team/players/register'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AccountRoute: typeof AccountRoute
  AdminRoute: typeof AdminRouteWithChildren
  AuthRoute: typeof AuthRouteWithChildren
  DashboardRoute: typeof DashboardRouteWithChildren
  HelpRoute: typeof HelpRoute
  LeaguesRoute: typeof LeaguesRouteWithChildren
  LiveRoute: typeof LiveRouteWithChildren
  TeamsRoute: typeof TeamsRouteWithChildren
  CommentateMatchIdRoute: typeof CommentateMatchIdRoute
  LegalPrivacyRoute: typeof LegalPrivacyRoute
  LegalTermsRoute: typeof LegalTermsRoute
  MatchesIdRoute: typeof MatchesIdRoute
  ModeratorMatchIdRoute: typeof ModeratorMatchIdRoute
  RefereeMatchIdRoute: typeof RefereeMatchIdRoute
  RegisterLeagueRoute: typeof RegisterLeagueRoute
  RegisterTeamRoute: typeof RegisterTeamRoute
  MatchesIndexRoute: typeof MatchesIndexRoute
  ShareMatchIdRoute: typeof ShareMatchIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/teams': {
      id: '/teams'
      path: '/teams'
      fullPath: '/teams'
      preLoaderRoute: typeof TeamsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/live': {
      id: '/live'
      path: '/live'
      fullPath: '/live'
      preLoaderRoute: typeof LiveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leagues': {
      id: '/leagues'
      path: '/leagues'
      fullPath: '/leagues'
      preLoaderRoute: typeof LeaguesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/help': {
      id: '/help'
      path: '/help'
      fullPath: '/help'
      preLoaderRoute: typeof HelpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account': {
      id: '/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/matches/': {
      id: '/matches/'
      path: '/matches'
      fullPath: '/matches/'
      preLoaderRoute: typeof MatchesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/teams/$slug': {
      id: '/teams/$slug'
      path: '/$slug'
      fullPath: '/teams/$slug'
      preLoaderRoute: typeof TeamsSlugRouteImport
      parentRoute: typeof TeamsRoute
    }
    '/register/team': {
      id: '/register/team'
      path: '/register/team'
      fullPath: '/register/team'
      preLoaderRoute: typeof RegisterTeamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register/league': {
      id: '/register/league'
      path: '/register/league'
      fullPath: '/register/league'
      preLoaderRoute: typeof RegisterLeagueRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/referee/$matchId': {
      id: '/referee/$matchId'
      path: '/referee/$matchId'
      fullPath: '/referee/$matchId'
      preLoaderRoute: typeof RefereeMatchIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/moderator/$matchId': {
      id: '/moderator/$matchId'
      path: '/moderator/$matchId'
      fullPath: '/moderator/$matchId'
      preLoaderRoute: typeof ModeratorMatchIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/matches/$id': {
      id: '/matches/$id'
      path: '/matches/$id'
      fullPath: '/matches/$id'
      preLoaderRoute: typeof MatchesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/live/$matchId': {
      id: '/live/$matchId'
      path: '/$matchId'
      fullPath: '/live/$matchId'
      preLoaderRoute: typeof LiveMatchIdRouteImport
      parentRoute: typeof LiveRoute
    }
    '/legal/terms': {
      id: '/legal/terms'
      path: '/legal/terms'
      fullPath: '/legal/terms'
      preLoaderRoute: typeof LegalTermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal/privacy': {
      id: '/legal/privacy'
      path: '/legal/privacy'
      fullPath: '/legal/privacy'
      preLoaderRoute: typeof LegalPrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leagues/$slug': {
      id: '/leagues/$slug'
      path: '/$slug'
      fullPath: '/leagues/$slug'
      preLoaderRoute: typeof LeaguesSlugRouteImport
      parentRoute: typeof LeaguesRoute
    }
    '/dashboard/viewer': {
      id: '/dashboard/viewer'
      path: '/viewer'
      fullPath: '/dashboard/viewer'
      preLoaderRoute: typeof DashboardViewerRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/teams': {
      id: '/dashboard/teams'
      path: '/teams'
      fullPath: '/dashboard/teams'
      preLoaderRoute: typeof DashboardTeamsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/team': {
      id: '/dashboard/team'
      path: '/team'
      fullPath: '/dashboard/team'
      preLoaderRoute: typeof DashboardTeamRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/sponsor': {
      id: '/dashboard/sponsor'
      path: '/sponsor'
      fullPath: '/dashboard/sponsor'
      preLoaderRoute: typeof DashboardSponsorRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/moderator': {
      id: '/dashboard/moderator'
      path: '/moderator'
      fullPath: '/dashboard/moderator'
      preLoaderRoute: typeof DashboardModeratorRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/leagues': {
      id: '/dashboard/leagues'
      path: '/leagues'
      fullPath: '/dashboard/leagues'
      preLoaderRoute: typeof DashboardLeaguesRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/league': {
      id: '/dashboard/league'
      path: '/league'
      fullPath: '/dashboard/league'
      preLoaderRoute: typeof DashboardLeagueRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/commentator': {
      id: '/dashboard/commentator'
      path: '/commentator'
      fullPath: '/dashboard/commentator'
      preLoaderRoute: typeof DashboardCommentatorRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/coach': {
      id: '/dashboard/coach'
      path: '/coach'
      fullPath: '/dashboard/coach'
      preLoaderRoute: typeof DashboardCoachRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/camera': {
      id: '/dashboard/camera'
      path: '/camera'
      fullPath: '/dashboard/camera'
      preLoaderRoute: typeof DashboardCameraRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/commentate/$matchId': {
      id: '/commentate/$matchId'
      path: '/commentate/$matchId'
      fullPath: '/commentate/$matchId'
      preLoaderRoute: typeof CommentateMatchIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof AuthRoute
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/slideshow': {
      id: '/admin/slideshow'
      path: '/slideshow'
      fullPath: '/admin/slideshow'
      preLoaderRoute: typeof AdminSlideshowRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/payments': {
      id: '/admin/payments'
      path: '/payments'
      fullPath: '/admin/payments'
      preLoaderRoute: typeof AdminPaymentsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/moderation': {
      id: '/admin/moderation'
      path: '/moderation'
      fullPath: '/admin/moderation'
      preLoaderRoute: typeof AdminModerationRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/ads': {
      id: '/admin/ads'
      path: '/ads'
      fullPath: '/admin/ads'
      preLoaderRoute: typeof AdminAdsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/share/match/$id': {
      id: '/share/match/$id'
      path: '/share/match/$id'
      fullPath: '/share/match/$id'
      preLoaderRoute: typeof ShareMatchIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/viewer/profile': {
      id: '/dashboard/viewer/profile'
      path: '/profile'
      fullPath: '/dashboard/viewer/profile'
      preLoaderRoute: typeof DashboardViewerProfileRouteImport
      parentRoute: typeof DashboardViewerRoute
    }
    '/dashboard/viewer/predictions': {
      id: '/dashboard/viewer/predictions'
      path: '/predictions'
      fullPath: '/dashboard/viewer/predictions'
      preLoaderRoute: typeof DashboardViewerPredictionsRouteImport
      parentRoute: typeof DashboardViewerRoute
    }
    '/dashboard/viewer/highlights': {
      id: '/dashboard/viewer/highlights'
      path: '/highlights'
      fullPath: '/dashboard/viewer/highlights'
      preLoaderRoute: typeof DashboardViewerHighlightsRouteImport
      parentRoute: typeof DashboardViewerRoute
    }
    '/dashboard/viewer/following': {
      id: '/dashboard/viewer/following'
      path: '/following'
      fullPath: '/dashboard/viewer/following'
      preLoaderRoute: typeof DashboardViewerFollowingRouteImport
      parentRoute: typeof DashboardViewerRoute
    }
    '/dashboard/viewer/chat': {
      id: '/dashboard/viewer/chat'
      path: '/chat'
      fullPath: '/dashboard/viewer/chat'
      preLoaderRoute: typeof DashboardViewerChatRouteImport
      parentRoute: typeof DashboardViewerRoute
    }
    '/dashboard/team/squad': {
      id: '/dashboard/team/squad'
      path: '/squad'
      fullPath: '/dashboard/team/squad'
      preLoaderRoute: typeof DashboardTeamSquadRouteImport
      parentRoute: typeof DashboardTeamRoute
    }
    '/dashboard/team/register': {
      id: '/dashboard/team/register'
      path: '/register'
      fullPath: '/dashboard/team/register'
      preLoaderRoute: typeof DashboardTeamRegisterRouteImport
      parentRoute: typeof DashboardTeamRoute
    }
    '/dashboard/team/profile': {
      id: '/dashboard/team/profile'
      path: '/profile'
      fullPath: '/dashboard/team/profile'
      preLoaderRoute: typeof DashboardTeamProfileRouteImport
      parentRoute: typeof DashboardTeamRoute
    }
    '/dashboard/team/media': {
      id: '/dashboard/team/media'
      path: '/media'
      fullPath: '/dashboard/team/media'
      preLoaderRoute: typeof DashboardTeamMediaRouteImport
      parentRoute: typeof DashboardTeamRoute
    }
    '/dashboard/team/matches': {
      id: '/dashboard/team/matches'
      path: '/matches'
      fullPath: '/dashboard/team/matches'
      preLoaderRoute: typeof DashboardTeamMatchesRouteImport
      parentRoute: typeof DashboardTeamRoute
    }
    '/dashboard/team/formations': {
      id: '/dashboard/team/formations'
      path: '/formations'
      fullPath: '/dashboard/team/formations'
      preLoaderRoute: typeof DashboardTeamFormationsRouteImport
      parentRoute: typeof DashboardTeamRoute
    }
    '/dashboard/moderator/var': {
      id: '/dashboard/moderator/var'
      path: '/var'
      fullPath: '/dashboard/moderator/var'
      preLoaderRoute: typeof DashboardModeratorVarRouteImport
      parentRoute: typeof DashboardModeratorRoute
    }
    '/dashboard/moderator/statistics': {
      id: '/dashboard/moderator/statistics'
      path: '/statistics'
      fullPath: '/dashboard/moderator/statistics'
      preLoaderRoute: typeof DashboardModeratorStatisticsRouteImport
      parentRoute: typeof DashboardModeratorRoute
    }
    '/dashboard/moderator/replay': {
      id: '/dashboard/moderator/replay'
      path: '/replay'
      fullPath: '/dashboard/moderator/replay'
      preLoaderRoute: typeof DashboardModeratorReplayRouteImport
      parentRoute: typeof DashboardModeratorRoute
    }
    '/dashboard/moderator/graphics': {
      id: '/dashboard/moderator/graphics'
      path: '/graphics'
      fullPath: '/dashboard/moderator/graphics'
      preLoaderRoute: typeof DashboardModeratorGraphicsRouteImport
      parentRoute: typeof DashboardModeratorRoute
    }
    '/dashboard/moderator/events': {
      id: '/dashboard/moderator/events'
      path: '/events'
      fullPath: '/dashboard/moderator/events'
      preLoaderRoute: typeof DashboardModeratorEventsRouteImport
      parentRoute: typeof DashboardModeratorRoute
    }
    '/dashboard/moderator/cameras': {
      id: '/dashboard/moderator/cameras'
      path: '/cameras'
      fullPath: '/dashboard/moderator/cameras'
      preLoaderRoute: typeof DashboardModeratorCamerasRouteImport
      parentRoute: typeof DashboardModeratorRoute
    }
    '/dashboard/moderator/broadcast': {
      id: '/dashboard/moderator/broadcast'
      path: '/broadcast'
      fullPath: '/dashboard/moderator/broadcast'
      preLoaderRoute: typeof DashboardModeratorBroadcastRouteImport
      parentRoute: typeof DashboardModeratorRoute
    }
    '/dashboard/moderator/announcements': {
      id: '/dashboard/moderator/announcements'
      path: '/announcements'
      fullPath: '/dashboard/moderator/announcements'
      preLoaderRoute: typeof DashboardModeratorAnnouncementsRouteImport
      parentRoute: typeof DashboardModeratorRoute
    }
    '/dashboard/league/wallet': {
      id: '/dashboard/league/wallet'
      path: '/wallet'
      fullPath: '/dashboard/league/wallet'
      preLoaderRoute: typeof DashboardLeagueWalletRouteImport
      parentRoute: typeof DashboardLeagueRoute
    }
    '/dashboard/league/teams': {
      id: '/dashboard/league/teams'
      path: '/teams'
      fullPath: '/dashboard/league/teams'
      preLoaderRoute: typeof DashboardLeagueTeamsRouteImport
      parentRoute: typeof DashboardLeagueRoute
    }
    '/dashboard/league/settings': {
      id: '/dashboard/league/settings'
      path: '/settings'
      fullPath: '/dashboard/league/settings'
      preLoaderRoute: typeof DashboardLeagueSettingsRouteImport
      parentRoute: typeof DashboardLeagueRoute
    }
    '/dashboard/league/rules': {
      id: '/dashboard/league/rules'
      path: '/rules'
      fullPath: '/dashboard/league/rules'
      preLoaderRoute: typeof DashboardLeagueRulesRouteImport
      parentRoute: typeof DashboardLeagueRoute
    }
    '/dashboard/league/register': {
      id: '/dashboard/league/register'
      path: '/register'
      fullPath: '/dashboard/league/register'
      preLoaderRoute: typeof DashboardLeagueRegisterRouteImport
      parentRoute: typeof DashboardLeagueRoute
    }
    '/dashboard/league/moderators': {
      id: '/dashboard/league/moderators'
      path: '/moderators'
      fullPath: '/dashboard/league/moderators'
      preLoaderRoute: typeof DashboardLeagueModeratorsRouteImport
      parentRoute: typeof DashboardLeagueRoute
    }
    '/dashboard/league/matches': {
      id: '/dashboard/league/matches'
      path: '/matches'
      fullPath: '/dashboard/league/matches'
      preLoaderRoute: typeof DashboardLeagueMatchesRouteImport
      parentRoute: typeof DashboardLeagueRoute
    }
    '/dashboard/league/broadcast': {
      id: '/dashboard/league/broadcast'
      path: '/broadcast'
      fullPath: '/dashboard/league/broadcast'
      preLoaderRoute: typeof DashboardLeagueBroadcastRouteImport
      parentRoute: typeof DashboardLeagueRoute
    }
    '/dashboard/league/$leagueId': {
      id: '/dashboard/league/$leagueId'
      path: '/$leagueId'
      fullPath: '/dashboard/league/$leagueId'
      preLoaderRoute: typeof DashboardLeagueLeagueIdRouteImport
      parentRoute: typeof DashboardLeagueRoute
    }
    '/dashboard/coach/training': {
      id: '/dashboard/coach/training'
      path: '/training'
      fullPath: '/dashboard/coach/training'
      preLoaderRoute: typeof DashboardCoachTrainingRouteImport
      parentRoute: typeof DashboardCoachRoute
    }
    '/dashboard/coach/tactics': {
      id: '/dashboard/coach/tactics'
      path: '/tactics'
      fullPath: '/dashboard/coach/tactics'
      preLoaderRoute: typeof DashboardCoachTacticsRouteImport
      parentRoute: typeof DashboardCoachRoute
    }
    '/dashboard/coach/squad': {
      id: '/dashboard/coach/squad'
      path: '/squad'
      fullPath: '/dashboard/coach/squad'
      preLoaderRoute: typeof DashboardCoachSquadRouteImport
      parentRoute: typeof DashboardCoachRoute
    }
    '/dashboard/coach/performance': {
      id: '/dashboard/coach/performance'
      path: '/performance'
      fullPath: '/dashboard/coach/performance'
      preLoaderRoute: typeof DashboardCoachPerformanceRouteImport
      parentRoute: typeof DashboardCoachRoute
    }
    '/dashboard/coach/medical': {
      id: '/dashboard/coach/medical'
      path: '/medical'
      fullPath: '/dashboard/coach/medical'
      preLoaderRoute: typeof DashboardCoachMedicalRouteImport
      parentRoute: typeof DashboardCoachRoute
    }
    '/dashboard/coach/matches': {
      id: '/dashboard/coach/matches'
      path: '/matches'
      fullPath: '/dashboard/coach/matches'
      preLoaderRoute: typeof DashboardCoachMatchesRouteImport
      parentRoute: typeof DashboardCoachRoute
    }
    '/dashboard/coach/lineups': {
      id: '/dashboard/coach/lineups'
      path: '/lineups'
      fullPath: '/dashboard/coach/lineups'
      preLoaderRoute: typeof DashboardCoachLineupsRouteImport
      parentRoute: typeof DashboardCoachRoute
    }
    '/dashboard/coach/formations': {
      id: '/dashboard/coach/formations'
      path: '/formations'
      fullPath: '/dashboard/coach/formations'
      preLoaderRoute: typeof DashboardCoachFormationsRouteImport
      parentRoute: typeof DashboardCoachRoute
    }
    '/dashboard/team/players/register': {
      id: '/dashboard/team/players/register'
      path: '/players/register'
      fullPath: '/dashboard/team/players/register'
      preLoaderRoute: typeof DashboardTeamPlayersRegisterRouteImport
      parentRoute: typeof DashboardTeamRoute
    }
  }
}

interface AdminRouteChildren {
  AdminAdsRoute: typeof AdminAdsRoute
  AdminModerationRoute: typeof AdminModerationRoute
  AdminPaymentsRoute: typeof AdminPaymentsRoute
  AdminSlideshowRoute: typeof AdminSlideshowRoute
  AdminUsersRoute: typeof AdminUsersRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAdsRoute: AdminAdsRoute,
  AdminModerationRoute: AdminModerationRoute,
  AdminPaymentsRoute: AdminPaymentsRoute,
  AdminSlideshowRoute: AdminSlideshowRoute,
  AdminUsersRoute: AdminUsersRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface AuthRouteChildren {
  AuthCallbackRoute: typeof AuthCallbackRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthCallbackRoute: AuthCallbackRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

interface DashboardCoachRouteChildren {
  DashboardCoachFormationsRoute: typeof DashboardCoachFormationsRoute
  DashboardCoachLineupsRoute: typeof DashboardCoachLineupsRoute
  DashboardCoachMatchesRoute: typeof DashboardCoachMatchesRoute
  DashboardCoachMedicalRoute: typeof DashboardCoachMedicalRoute
  DashboardCoachPerformanceRoute: typeof DashboardCoachPerformanceRoute
  DashboardCoachSquadRoute: typeof DashboardCoachSquadRoute
  DashboardCoachTacticsRoute: typeof DashboardCoachTacticsRoute
  DashboardCoachTrainingRoute: typeof DashboardCoachTrainingRoute
}

const DashboardCoachRouteChildren: DashboardCoachRouteChildren = {
  DashboardCoachFormationsRoute: DashboardCoachFormationsRoute,
  DashboardCoachLineupsRoute: DashboardCoachLineupsRoute,
  DashboardCoachMatchesRoute: DashboardCoachMatchesRoute,
  DashboardCoachMedicalRoute: DashboardCoachMedicalRoute,
  DashboardCoachPerformanceRoute: DashboardCoachPerformanceRoute,
  DashboardCoachSquadRoute: DashboardCoachSquadRoute,
  DashboardCoachTacticsRoute: DashboardCoachTacticsRoute,
  DashboardCoachTrainingRoute: DashboardCoachTrainingRoute,
}

const DashboardCoachRouteWithChildren = DashboardCoachRoute._addFileChildren(
  DashboardCoachRouteChildren,
)

interface DashboardLeagueRouteChildren {
  DashboardLeagueLeagueIdRoute: typeof DashboardLeagueLeagueIdRoute
  DashboardLeagueBroadcastRoute: typeof DashboardLeagueBroadcastRoute
  DashboardLeagueMatchesRoute: typeof DashboardLeagueMatchesRoute
  DashboardLeagueModeratorsRoute: typeof DashboardLeagueModeratorsRoute
  DashboardLeagueRegisterRoute: typeof DashboardLeagueRegisterRoute
  DashboardLeagueRulesRoute: typeof DashboardLeagueRulesRoute
  DashboardLeagueSettingsRoute: typeof DashboardLeagueSettingsRoute
  DashboardLeagueTeamsRoute: typeof DashboardLeagueTeamsRoute
  DashboardLeagueWalletRoute: typeof DashboardLeagueWalletRoute
}

const DashboardLeagueRouteChildren: DashboardLeagueRouteChildren = {
  DashboardLeagueLeagueIdRoute: DashboardLeagueLeagueIdRoute,
  DashboardLeagueBroadcastRoute: DashboardLeagueBroadcastRoute,
  DashboardLeagueMatchesRoute: DashboardLeagueMatchesRoute,
  DashboardLeagueModeratorsRoute: DashboardLeagueModeratorsRoute,
  DashboardLeagueRegisterRoute: DashboardLeagueRegisterRoute,
  DashboardLeagueRulesRoute: DashboardLeagueRulesRoute,
  DashboardLeagueSettingsRoute: DashboardLeagueSettingsRoute,
  DashboardLeagueTeamsRoute: DashboardLeagueTeamsRoute,
  DashboardLeagueWalletRoute: DashboardLeagueWalletRoute,
}

const DashboardLeagueRouteWithChildren = DashboardLeagueRoute._addFileChildren(
  DashboardLeagueRouteChildren,
)

interface DashboardModeratorRouteChildren {
  DashboardModeratorAnnouncementsRoute: typeof DashboardModeratorAnnouncementsRoute
  DashboardModeratorBroadcastRoute: typeof DashboardModeratorBroadcastRoute
  DashboardModeratorCamerasRoute: typeof DashboardModeratorCamerasRoute
  DashboardModeratorEventsRoute: typeof DashboardModeratorEventsRoute
  DashboardModeratorGraphicsRoute: typeof DashboardModeratorGraphicsRoute
  DashboardModeratorReplayRoute: typeof DashboardModeratorReplayRoute
  DashboardModeratorStatisticsRoute: typeof DashboardModeratorStatisticsRoute
  DashboardModeratorVarRoute: typeof DashboardModeratorVarRoute
}

const DashboardModeratorRouteChildren: DashboardModeratorRouteChildren = {
  DashboardModeratorAnnouncementsRoute: DashboardModeratorAnnouncementsRoute,
  DashboardModeratorBroadcastRoute: DashboardModeratorBroadcastRoute,
  DashboardModeratorCamerasRoute: DashboardModeratorCamerasRoute,
  DashboardModeratorEventsRoute: DashboardModeratorEventsRoute,
  DashboardModeratorGraphicsRoute: DashboardModeratorGraphicsRoute,
  DashboardModeratorReplayRoute: DashboardModeratorReplayRoute,
  DashboardModeratorStatisticsRoute: DashboardModeratorStatisticsRoute,
  DashboardModeratorVarRoute: DashboardModeratorVarRoute,
}

const DashboardModeratorRouteWithChildren =
  DashboardModeratorRoute._addFileChildren(DashboardModeratorRouteChildren)

interface DashboardTeamRouteChildren {
  DashboardTeamFormationsRoute: typeof DashboardTeamFormationsRoute
  DashboardTeamMatchesRoute: typeof DashboardTeamMatchesRoute
  DashboardTeamMediaRoute: typeof DashboardTeamMediaRoute
  DashboardTeamProfileRoute: typeof DashboardTeamProfileRoute
  DashboardTeamRegisterRoute: typeof DashboardTeamRegisterRoute
  DashboardTeamSquadRoute: typeof DashboardTeamSquadRoute
  DashboardTeamPlayersRegisterRoute: typeof DashboardTeamPlayersRegisterRoute
}

const DashboardTeamRouteChildren: DashboardTeamRouteChildren = {
  DashboardTeamFormationsRoute: DashboardTeamFormationsRoute,
  DashboardTeamMatchesRoute: DashboardTeamMatchesRoute,
  DashboardTeamMediaRoute: DashboardTeamMediaRoute,
  DashboardTeamProfileRoute: DashboardTeamProfileRoute,
  DashboardTeamRegisterRoute: DashboardTeamRegisterRoute,
  DashboardTeamSquadRoute: DashboardTeamSquadRoute,
  DashboardTeamPlayersRegisterRoute: DashboardTeamPlayersRegisterRoute,
}

const DashboardTeamRouteWithChildren = DashboardTeamRoute._addFileChildren(
  DashboardTeamRouteChildren,
)

interface DashboardViewerRouteChildren {
  DashboardViewerChatRoute: typeof DashboardViewerChatRoute
  DashboardViewerFollowingRoute: typeof DashboardViewerFollowingRoute
  DashboardViewerHighlightsRoute: typeof DashboardViewerHighlightsRoute
  DashboardViewerPredictionsRoute: typeof DashboardViewerPredictionsRoute
  DashboardViewerProfileRoute: typeof DashboardViewerProfileRoute
}

const DashboardViewerRouteChildren: DashboardViewerRouteChildren = {
  DashboardViewerChatRoute: DashboardViewerChatRoute,
  DashboardViewerFollowingRoute: DashboardViewerFollowingRoute,
  DashboardViewerHighlightsRoute: DashboardViewerHighlightsRoute,
  DashboardViewerPredictionsRoute: DashboardViewerPredictionsRoute,
  DashboardViewerProfileRoute: DashboardViewerProfileRoute,
}

const DashboardViewerRouteWithChildren = DashboardViewerRoute._addFileChildren(
  DashboardViewerRouteChildren,
)

interface DashboardRouteChildren {
  DashboardCameraRoute: typeof DashboardCameraRoute
  DashboardCoachRoute: typeof DashboardCoachRouteWithChildren
  DashboardCommentatorRoute: typeof DashboardCommentatorRoute
  DashboardLeagueRoute: typeof DashboardLeagueRouteWithChildren
  DashboardLeaguesRoute: typeof DashboardLeaguesRoute
  DashboardModeratorRoute: typeof DashboardModeratorRouteWithChildren
  DashboardSponsorRoute: typeof DashboardSponsorRoute
  DashboardTeamRoute: typeof DashboardTeamRouteWithChildren
  DashboardTeamsRoute: typeof DashboardTeamsRoute
  DashboardViewerRoute: typeof DashboardViewerRouteWithChildren
  DashboardIndexRoute: typeof DashboardIndexRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardCameraRoute: DashboardCameraRoute,
  DashboardCoachRoute: DashboardCoachRouteWithChildren,
  DashboardCommentatorRoute: DashboardCommentatorRoute,
  DashboardLeagueRoute: DashboardLeagueRouteWithChildren,
  DashboardLeaguesRoute: DashboardLeaguesRoute,
  DashboardModeratorRoute: DashboardModeratorRouteWithChildren,
  DashboardSponsorRoute: DashboardSponsorRoute,
  DashboardTeamRoute: DashboardTeamRouteWithChildren,
  DashboardTeamsRoute: DashboardTeamsRoute,
  DashboardViewerRoute: DashboardViewerRouteWithChildren,
  DashboardIndexRoute: DashboardIndexRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

interface LeaguesRouteChildren {
  LeaguesSlugRoute: typeof LeaguesSlugRoute
}

const LeaguesRouteChildren: LeaguesRouteChildren = {
  LeaguesSlugRoute: LeaguesSlugRoute,
}

const LeaguesRouteWithChildren =
  LeaguesRoute._addFileChildren(LeaguesRouteChildren)

interface LiveRouteChildren {
  LiveMatchIdRoute: typeof LiveMatchIdRoute
}

const LiveRouteChildren: LiveRouteChildren = {
  LiveMatchIdRoute: LiveMatchIdRoute,
}

const LiveRouteWithChildren = LiveRoute._addFileChildren(LiveRouteChildren)

interface TeamsRouteChildren {
  TeamsSlugRoute: typeof TeamsSlugRoute
}

const TeamsRouteChildren: TeamsRouteChildren = {
  TeamsSlugRoute: TeamsSlugRoute,
}

const TeamsRouteWithChildren = TeamsRoute._addFileChildren(TeamsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AccountRoute: AccountRoute,
  AdminRoute: AdminRouteWithChildren,
  AuthRoute: AuthRouteWithChildren,
  DashboardRoute: DashboardRouteWithChildren,
  HelpRoute: HelpRoute,
  LeaguesRoute: LeaguesRouteWithChildren,
  LiveRoute: LiveRouteWithChildren,
  TeamsRoute: TeamsRouteWithChildren,
  CommentateMatchIdRoute: CommentateMatchIdRoute,
  LegalPrivacyRoute: LegalPrivacyRoute,
  LegalTermsRoute: LegalTermsRoute,
  MatchesIdRoute: MatchesIdRoute,
  ModeratorMatchIdRoute: ModeratorMatchIdRoute,
  RefereeMatchIdRoute: RefereeMatchIdRoute,
  RegisterLeagueRoute: RegisterLeagueRoute,
  RegisterTeamRoute: RegisterTeamRoute,
  MatchesIndexRoute: MatchesIndexRoute,
  ShareMatchIdRoute: ShareMatchIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
